### ISSUE TITLE
[Feature] 能否分离UI界面到单独的仓库方便前端开发提交贡献?

### ISSUE THREAD

**Issue by you-hengh** [usual2970/certimate#101]
**功能描述**
能否分离UI界面到单独的仓库方便前端开发提交贡献?

**动机**
为什么这个功能对项目有帮助？
对后端不熟悉, 也不想fork太多无关代码,分离UI到单独仓库后, 前后端开发都可以直接fork自己感兴趣的仓库进行提交贡献

**替代方案**
描述你已经考虑过的替代方案。
新开一个项目的UI仓库

**Comment by usual2970** [comment]
感谢反馈～目前项目就是前后端分离的，只是放在了同一个仓库

这样做的目的是为了把前端页面打包到二进制文件里，方便用户部署

你可以放心大胆的提交PR，我会 review 的，Certimate 鼓励大家参与进来
