### ISSUE TITLE
[Feature] 一个证书任务同时支持多个部署服务

### ISSUE THREAD

**Issue by linsir** [usual2970/certimate#102]
**功能描述**
申请一个泛域名证书多个地方使用，希望同一个证书任务同时支持多个部署服务（可以是多类型）。

**动机**
申请一个泛域名证书多个地方使用

**替代方案**
建立多个证书管理任务

**其他信息**

**Comment by usual2970** [comment]
感谢反馈～ 可使用 v0.2.0

注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改
