### ISSUE TITLE
[Feature] 能否支持K8s的部署

### ISSUE THREAD

**Issue by PittyXu** [usual2970/certimate#103]
**功能描述**
该项目可以部署在K8s里，给该项目赋予ServerAccount权限这样可以将证书写到Secret里。
如SSH组一样，可以把泛域名的证书写到多个命名空间的Secret里。

**动机**
我们很多域名管理是在K8s Ingress上

**替代方案**
现在用的cert-manager

**Comment by usual2970** [comment]
已支持 v0.2.4，感谢 @fudiwei
