### ISSUE TITLE
[Bug] 部署到服务器的时候提示：failed to upload certificate: failed to open remote file: sftp: "Failure" (SSH_FX_FAILURE)

### ISSUE THREAD

**Issue by 948559046** [usual2970/certimate#115]
![image](https://github.com/user-attachments/assets/335f6d7b-4c0f-4cff-9ba7-db233185834e)

不知道哪一步出问题了，服务器是确认可以登录的

**Comment by usual2970** [comment]
感谢反馈～ 具体配置是什么也提供一下，不然全靠猜

可以到群里反馈一下

**Comment by MrChihiro** [comment]
加上证书名称即可
![image](https://github.com/user-attachments/assets/83822587-fc11-491d-9caa-d29055bc6d5e)
