### ISSUE TITLE
[Feature] 希望能支持配置访问前缀

### ISSUE THREAD

**Issue by Lilaccoral** [usual2970/certimate#118]
**功能描述**
支持配置访问前缀，从nginx转发的时候可能需要

**动机**
配置到某个域名下的子目录时需要

**替代方案**

**其他信息**

**Comment by usual2970** [comment]
感谢反馈～但是没理解你的意思😀

这个 issue 我关了，你可以重开一个详细描述你的需求

**Comment by Lilaccoral** [comment]
👌我再想想吧
