### ISSUE TITLE
[Feature] Docker images 构建优化

### ISSUE THREAD

**Issue by l123wx** [usual2970/certimate#122]
我注意到每次前端更新的时候都要手动提交 commit 把前端构建后的代码提交到仓库，怎么不把构建前端的步骤也放到 Dockerfile 里面呢？😂😂😂

**Comment by usual2970** [comment]
😀理由如下：
1. build 工作并不繁重，你还可以顺便检查一下开发结果
2. 对于不懂前端的同学，拿到源码后直接 go run main.go serve就行了

当然了，看起来不符合前端开发的最佳实践，不影响开发效率就可以了。
