### ISSUE TITLE
[Feature] 希望授权管理能新增复制按钮一键复制

### ISSUE THREAD

**Issue by xjpz** [usual2970/certimate#124]
**功能描述**
一台服务器部署了很多服务对应很多域名，只是二级域名不一样，其他的配置都一样一键复制之后只改子域名部分就能快速配置好

**动机**
配置方便

**替代方案**
一个个新增授权

**其他信息**
在这里添加任何相关的附加信息或截图。
![WX20240930-111943](https://github.com/user-attachments/assets/9f6bee12-65b1-46a2-9b8a-2482d55febc6)

**Comment by usual2970** [comment]
已支持 v0.1.15
