### ISSUE TITLE
阿里云申请证书失败

### ISSUE THREAD

**Issue by phm123417** [usual2970/certimate#126]
**描述问题**
阿里云域名申请证书失败

错误日志(error: one or more domains had a problem: [yan-test.katchu.cn] propagation: time limit exceeded: last error: [zone=katchu.cn.] could not determine authoritative nameservers)

**Comment by phm123417** [comment]
没有哦，我申请cloudflare的域名证书就可以成功，就是阿里云的没成功，等几天了还是这样子

**Comment by usual2970** [comment]
感谢反馈～ 应该是获取 dns 解析时超时了，可以尝试配置不同的 nameserver 解决

后续我们会考虑加个自定义超时时间

具体可以到群里面反馈

**Comment by xeahsoon** [comment]
> 感谢反馈～ 应该是获取 dns 解析时超时了，可以尝试配置不同的 nameserver 解决
> 
> 后续我们会考虑加个自定义超时时间
> 
> 具体可以到群里面反馈

具体要如何配置不同的 nameserver 呢
