### ISSUE TITLE
[Bug] 腾讯云部署失败

### ISSUE THREAD

**Issue by frankxjkuang** [usual2970/certimate#129]
**描述问题**
申请证书成功，第一次部署的时候失败，按照提示进行了授权，再次部署的时候又失败，错误信息：证书不可以部署到实例列表下，详见下面截图

**复现步骤**
复现该问题的步骤：
1. 域名列表
2. 立即部署

**期望的结果**
不知道是什么原因，如何解决

**截图**
![image](https://github.com/user-attachments/assets/7d5a2bc5-3898-4b78-8424-d66178c3b93e)

**环境**
- 操作系统: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- 浏览器: Chrome版本 129.0.6668.60（正式版本） (x86_64)
- 仓库版本: image: registry.cn-shanghai.aliyuncs.com/usual2970/certimate:latest

**Comment by usual2970** [comment]
感谢反馈～应该是部署到腾讯 cdn 时没有找到对应域名的 cdn 实例

具体情况还要看你的详细配置，可以到群里面反馈
