### ISSUE TITLE
[Feature] 希望支持ecc证书

### ISSUE THREAD

**Issue by fzlee** [usual2970/certimate#132]
**功能描述**
希望可以申请ecc证书

**动机**
ecc证书性能要好很多

**Comment by JavaSCU** [comment]
附议~~！

**Comment by fudiwei** [comment]
我可以实现这个功能。

现在需要确认一个需求是，证书签名算法这个参数是期望在系统设置里做成一个全局配置，还是在域名管理里为每个域名单独配置？@usual2970

**Comment by usual2970** [comment]
已支持 v0.2.2, 感谢 @fudiwei 同学🤙🤙
