### ISSUE TITLE
点击部署  步骤-检查 状态-失败 没有显示操作日志

### ISSUE THREAD

**Issue by gexin1** [usual2970/certimate#14]
![image](https://github.com/user-attachments/assets/812bfcdc-6d4f-479e-aac8-3fd7256108db)
docker容器log 检查了一下 也没有出现日志
请问一下该如何排查呢

**Comment by usual2970** [comment]
![WX20240910-165055](https://github.com/user-attachments/assets/d61b2dce-643a-477d-a2cd-4bacf0f3d1e1)
可在 部署历史 找到对应域名的部署历史 点击日志查看原因

**Comment by gexin1** [comment]
![image](https://github.com/user-attachments/assets/bfa1f65d-bbf2-4759-8a1c-a26f39bce3dd)
没有内容显示
我本地环境是windows11  
docker desktop  `Current version: 4.31.1 (153621)`

**Comment by usual2970** [comment]
这里沟通效率有点低，可以考虑加我微信

<image src="https://github.com/user-attachments/assets/72301fa8-af05-462e-bfeb-6caffc583aa9" width="400"/>

**Comment by gexin1** [comment]
好的 感谢
