### ISSUE TITLE
部署阿里云OSS报错

### ISSUE THREAD

**Issue by linganmin** [usual2970/certimate#17]
SDKError: StatusCode: 400 Code: MissingStatus Message: code: 400, Status is mandatory for this action. request id: 1A31BBF1-6C7D-5A4D-A3FA-C834B3F10718 Data: {"Code":"MissingStatus","HostId":"cas.aliyuncs.com","Message":"Status is mandatory for this action.","Recommend":"https://api.aliyun.com/troubleshoot?q=MissingStatus\u0026product=cas\u0026requestId=1A31BBF1-6C7D-5A4D-A3FA-C834B3F10718","RequestId":"1A31BBF1-6C7D-5A4D-A3FA-C834B3F10718","statusCode":400}

**Comment by usual2970** [comment]
阿里云OSS部署上传的证书有限制

https://help.aliyun.com/zh/ssl-certificate/product-overview/billing-overview?spm=5176.2020520163.console-base_help.dexternal.73533711mSUB7z

**Comment by mnixry** [comment]
> 阿里云OSS部署上传的证书有限制

@usual2970 如果我没有理解错您提供的文档的话，这是否意味着使用程序现有的操作流程（使用 DNS 验证申请 Let's Encrypt 的证书并上传到阿里云，再通过 CAS 的部署功能应用到 OSS）是无法免费进行该操作的，而需要支付 30元/次的部署费用。

能否提供一些其他的替代方案，比如使用 https://api.aliyun.com/api/Oss/2019-05-17/PutCname API 来完成该操作（看起来可以参考 https://github.com/nekoimi/oss-auto-cert 仓库的实现），谢谢。

**Comment by usual2970** [comment]
@mnixry 
> 能否提供一些其他的替代方案，比如使用 https://api.aliyun.com/api/Oss/2019-05-17/PutCname API 来完成该操作（看起来可以参考 https://github.com/nekoimi/oss-auto-cert 仓库的实现），谢谢。

试了下这个接口可以用的，已更新到最新版本 V0.2.0
