### ISSUE TITLE
[Feature] 希望在添加ssh部署的时候可以识别自定义hosts名称

### ISSUE THREAD

**Issue by ljwtorch** [usual2970/certimate#172]
**功能描述**
授权管理页面——SSH部署——服务器Host这个部分可以识别自定义的hosts名称，例如宿主机/etc/hosts文件中：
```
10.1.1.110 test-ecs
```

**动机**
可以通过配置宿主机的hosts文件，避免因后期服务器ip修改导致配置需要重新修改的情况

**Comment by usual2970** [comment]
感谢反馈～ 没明白你的意思，这个 Issue 先关了，可以重开一个详细描述需求
