### ISSUE TITLE
[Feature] certimate自身支持https

### ISSUE THREAD

**Issue by JavaSCU** [usual2970/certimate#175]
**功能描述**
certimate自身服务支持https方式部署，并可通过自身证书管理服务来更新

**动机**
网络安全

**Comment by usual2970** [comment]
运行 
> ./certimate serve 你的域名

会自动给你的域名添加证书

**Comment by lxjmaster** [comment]
> > 运行
> > > ./certimate serve 你的域名
> > 
> > 
> > 会自动给你的域名添加证书
> 
> > 运行
> > > ./certimate serve 你的域名
> > 
> > 
> > 会自动给你的域名添加证书
> 
> docker方式部署的如何添加呢？

我也想知道docker部署的如何添加
