### ISSUE TITLE
[Feature] 一个证书支持多个主机名称

### ISSUE THREAD

**Issue by JavaSCU** [usual2970/certimate#178]
**功能描述**
例如
DNS Name=*.xxx.net
DNS Name=xxx.net

**动机**
一个多主机名证书在实际使用中很常见

**替代方案**
无

**Comment by usual2970** [comment]
现在就支持

**Comment by JavaSCU** [comment]
> 现在就支持

怎么设置呢？域名字段输入多个，用什么间隔？README里面似乎没找到说明

**Comment by JavaSCU** [comment]
发现要升级到v0.20就支持了，建议文档也更新更新
