### ISSUE TITLE
[Feature] 支持跨账号（服务商）申请证书

### ISSUE THREAD

**Issue by mumudm** [usual2970/certimate#179]
**功能描述**
域名在 A 账号中，但是证书再 B 账号中管理，希望 B 账号也能申请证书
**动机**
一个账号的免费额度用完了，只能用其他账号申请了 (┬＿┬)

**Comment by LeoChen98** [comment]
问题是证书申请不走平台啊？只是上传证书到平台而已。不涉及免费额度。

**Comment by usual2970** [comment]
感谢反馈～ 没明白你的意思

申请的证书即不在你的 A 账户中，也不在 B 账户中
