### ISSUE TITLE
申请增加泛域名支持及自定义申请证书时邮箱地址的功能

### ISSUE THREAD

**Issue by o2asdv** [usual2970/certimate#18]
申请进行下列改进:
     1、在添加域名时，可选择申请泛域名证书，申请时同时申请：“a.com”和“*.a.com”
     2、配置页面内增加自定义申请证书时邮箱地址的功能

**Comment by usual2970** [comment]
已支持 v0.1.6

**Comment by usual2970** [comment]
[域名变量及授权组介绍](https://docs.certimate.me/blog/multi-deployer/)

**Comment by o2asdv** [comment]
没看到有泛域名的选项。请问泛域名如何设置，在域名里输入多个，比如a.com,*.a.com?
