### ISSUE TITLE
[Feature] 本地部署希望也加入域名变量支持

### ISSUE THREAD

**Issue by FrankEvil** [usual2970/certimate#181]
**功能描述**
域名变量功能很有用，但是现在只能在ssh中使用 希望在本地部署中也加入  授权组也能加入本地就好了
![image](https://github.com/user-attachments/assets/a3df8e5e-ef05-4ebc-a5ec-f947eb269545)

**Comment by imaxwen** [comment]
同样需求 +1 👍🏻

**Comment by usual2970** [comment]
可以使用 v0.2.0

注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改
