### ISSUE TITLE
问题咨询：同一个域名如何部署到多个云服务下？

### ISSUE THREAD

**Issue by fudiwei** [usual2970/certimate#182]
感谢作者开源，很棒的项目。

有一个问题我想咨询一下，假如我有一个域名的 SSL 证书，需要同时部署到多个云服务下，该如何操作？

如下图所示的地方似乎只能单选。

![image](https://github.com/user-attachments/assets/ab76b186-a271-46de-bc48-1e349d432b00)

**Comment by usual2970** [comment]
感谢反馈～目前同一个证书部署到多个主机

目前正在改版，改版后支持一个证书部署到任意多个服务

**Comment by usual2970** [comment]
已支持 v0.2.0 

注意 v0.2.0 对 v0.1.xx系列进行一些不向后兼容的修改
