### ISSUE TITLE
[Bug] 单个证书部署到两个服务器上报错

### ISSUE THREAD

**Issue by ljwtorch** [usual2970/certimate#185]
**描述问题**
单个证书部署到两个服务器上报错，一开始因为目标服务器防火墙端口限制未关闭导致部署失败，然后重新点击部署后没有部署日志产生，点击侧边栏控制面板和部署历史会出现报错

**复现步骤**
点击侧边栏控制面板和部署历史会出现报错

**期望的结果**
显示对应页面

**截图**
![image](https://github.com/user-attachments/assets/a6a7eca0-3e6d-471e-9e3c-f80477ce1d35)

**环境**
- 操作系统: macos15.1
- 浏览器: chrome
- 仓库版本: v0.1.18

**Comment by usual2970** [comment]
感谢反馈～应该是操作过程中产生了脏数据

具体可以加作者好友，提供更多细节
