### ISSUE TITLE
阿里云OSS部署失败

### ISSUE THREAD

**Issue by hutaoseven** [usual2970/certimate#186]
Ubuntu 24.04
Version 0.1.19

阿里云OSS部署失败

`SDKError: StatusCode: 400 Code: MissingStatus Message: code: 400, Status is mandatory for this action. request id: 0A9672F1-AFA7-57A7-8B43-5F0DE9CEA02F Data: {"Code":"MissingStatus","HostId":"cas.aliyuncs.com","Message":"Status is mandatory for this action.","Recommend":"https://api.aliyun.com/troubleshoot?q=MissingStatus&product=cas&requestId=0A9672F1-AFA7-57A7-8B43-5F0DE9CEA02F","RequestId":"0A9672F1-AFA7-57A7-8B43-5F0DE9CEA02F","statusCode":400}`

**Comment by hutaoseven** [comment]
![image](https://github.com/user-attachments/assets/2bdaddf7-a579-4915-97db-dde2528c9b20)

**Comment by hutaoseven** [comment]
![image](https://github.com/user-attachments/assets/0f55bf0b-9355-4c51-b870-971b8f114944)

**Comment by hutaoseven** [comment]
![image](https://github.com/user-attachments/assets/be6404c4-c9d1-4d32-b538-f8b4600d0cf0)

**Comment by usual2970** [comment]
感谢反馈～ 可以使用最新版本 v0.2.0
