### ISSUE TITLE
数据库连接对接外部数据库

### ISSUE THREAD

**Issue by lsx1205** [usual2970/certimate#187]
**功能描述**
您好，我初次使用certimate这个产品，了解到数据库使用的sqlite的方式，我之前使用uptime kuma这个产品用来实现监控一些内网域名，它也是使用sqlite，但是我感觉这种形式需要考虑到去备份db文件，增加了一个额外去备份的点

**动机**
对接外部的数据库，不管是云上数据库，还是自建的数据库，都减少了一个额外备份db的点，当然，也会增大代码编写成本

**Comment by usual2970** [comment]
感谢反馈～ Certimate目前使用 sqlite，后续没有支持其他数据库的计划
