### ISSUE TITLE
[Bug] 申请域名颁发者的公用名是R10，浏览器不认，说证书不安全

### ISSUE THREAD

**Issue by wf58585858** [usual2970/certimate#189]
**描述问题**
在宝塔显示证书分类是其他分类，wget请求说域名不匹配，只有我一个人遇到？
└─[0] <> wget https://tg.xxxxx.com/request_record.php
--2024-10-12 19:22:01--  https://tg.xxxxx.com/request_record.php
Resolving tg.xxxxx.com (tg.xxxxx.com)... 47.238.456.101
Connecting to tg.xxxxx.com (tg.xxxxx.com)|47.238.456.101|:443... connected.
The certificate's owner does not match hostname ‘tg.xxxxx.com’

**Comment by usual2970** [comment]
> The certificate's owner does not match hostname ‘tg.xxxxx.com’

原因告诉你了😅

**Comment by wf58585858** [comment]
这个我也看到了
我意思是宝塔上的认证域名显示的是对的
到期时间这些申请时间这些都对得上
浏览器查看证书信息也都是对的
但是浏览器就是提示证书不对

你们这个申请是泛域名吧？
就是使用设置DNS的校验的那种？
