### ISSUE TITLE
[Feature] 希望在添加ssh部署的时可以识别宿主机hosts文件中的解析内容

### ISSUE THREAD

**Issue by ljwtorch** [usual2970/certimate#191]
**功能描述**
授权管理页面——SSH部署——服务器Host这个部分可以识别自定义的hosts名称；

例如我对宿主机/etc/hosts文件进行编辑：
```
10.1.1.110 test-ecs
```

然后在服务器host这一个框中输入test-ecs，目前会提示：
![image](https://github.com/user-attachments/assets/6539518c-ba89-429e-9097-e964fb4640c2)

我希望"test-ecs"能正常输入，并解析为10.1.1.110这个ip

**动机**
可以通过配置宿主机的hosts文件，避免因后期服务器ip更改导致配置需要重新修改的情况

**Comment by usual2970** [comment]
这里可以填域名的，自定义的 hosts 改成域名形式就可以了
