### ISSUE TITLE
[Feature] web页面优化

### ISSUE THREAD

**Issue by C018** [usual2970/certimate#192]
**功能描述**
简要描述你希望添加的功能和相关问题。
web页面需要做下屏幕大小优化，适配缩放啥的，不然ui很多东西都超出屏幕显示范围了，比如说13.3寸1080p屏幕windows系统缩放125%，在添加添加授权的时候服务商几个字都看不见了，右下角翻页和[文档](https://docs.certimate.me/)
[Certimate v0.2.0](https://github.com/usual2970/certimate/releases)这俩模块重合了，翻页都点不到。只能在浏览器继续缩放才能正常使用。
**动机**
为什么这个功能对项目有帮助？
增加ui适配屏幕，对使用有帮助
**替代方案**
描述你已经考虑过的替代方案。
添加相应的ui适配代码
**其他信息**
在这里添加任何相关的附加信息或截图。
![image](https://github.com/user-attachments/assets/b5bb2be7-8b6d-4f2f-a594-a17a6236ade9)
![image](https://github.com/user-attachments/assets/f3ee2ca1-d69d-4fb1-84fd-0642c80a4a51)

**Comment by usual2970** [comment]
已完善 v0.2.5

**Comment by C018** [comment]
谢谢，我这边更新试试。
