### ISSUE TITLE
[Feature] 添加ssh部署的密钥密码功能

### ISSUE THREAD

**Issue by lsx1205** [usual2970/certimate#194]
**功能描述**
在使用ssh部署时，目标主机只能使用密钥+密钥密码登录，禁止使用用户名+密码形式。希望增加密钥+密钥密码的形式，辛苦老哥🌹

<img width="733" alt="image" src="https://github.com/user-attachments/assets/afe66fe5-1433-4b0d-b2c6-9bb5c393aea4">

**Comment by fudiwei** [comment]
@usual2970 closed by #206

**Comment by usual2970** [comment]
已支持 v0.2.2, 感谢 @fudiwei
