### ISSUE TITLE
[Feature] 阿里云@域名和www证书不通用

### ISSUE THREAD

**Issue by animeic** [usual2970/certimate#195]
**功能描述**
比如阿里云手动申请的证书@和www是可以通用的。网站配置也是一起配置的，希望申请的证书@和www和手动的保持一致能通用。

**Comment by usual2970** [comment]
感谢反馈～具体细节提供一下呢，比如你怎么配置的

可以加入微信群，让更多同学帮助

**Comment by fuuhoo** [comment]
请问这个解决了么？我申请不带www的域名，然后访问www的不行呢

**Comment by fuuhoo** [comment]
> 请问这个解决了么？我申请不带www的域名，然后访问www的不行呢

添加域名的时候就要带上www
