### ISSUE TITLE
[Feature]希望支持百度云域名

### ISSUE THREAD

**Issue by Joshuacsj** [usual2970/certimate#196]
**功能描述**
简要描述你希望添加的功能和相关问题。

**动机**
为什么这个功能对项目有帮助？

**替代方案**
描述你已经考虑过的替代方案。

**其他信息**
在这里添加任何相关的附加信息或截图。

**Comment by usual2970** [comment]
感谢反馈～ 后续没有这方面的迭代计划

欢迎提交 PR
