### ISSUE TITLE
[Feature] 增加剩余多少天过期的功能

### ISSUE THREAD

**Issue by qywk99** [usual2970/certimate#199]
**功能描述**
简要描述你希望添加的功能和相关问题。

增加剩余多少天过期的功能

**动机**
为什么这个功能对项目有帮助？
能直观的看到还有多少天过期。
![image](https://github.com/user-attachments/assets/f20bdb47-fa9c-46f1-a9f7-77e0a4a106f7)

**替代方案**
描述你已经考虑过的替代方案。

**其他信息**
在这里添加任何相关的附加信息或截图。

**Comment by usual2970** [comment]
已支持 v0.2.5
