### ISSUE TITLE
ssh部署错误

### ISSUE THREAD

**Issue by hausen1012** [usual2970/certimate#2]
![image](https://github.com/user-attachments/assets/b5d41b0c-1c4f-436f-a1d5-8dc6a981c94f)

![image](https://github.com/user-attachments/assets/af112f60-b8ab-430d-968e-0358cecd5d72)
![image](https://github.com/user-attachments/assets/2b7c1ad4-5c9a-47b2-b267-851c713f50f0)

**Comment by usual2970** [comment]
已修复 [v0.0.8](https://github.com/usual2970/certimate/releases/tag/v0.0.8)

**Comment by hausen1012** [comment]
> 已修复 [v0.0.8](https://github.com/usual2970/certimate/releases/tag/v0.0.8)

docker 镜像有自动更新么？
