### ISSUE TITLE
[Feature] 通知测试

### ISSUE THREAD

**Issue by qywk99** [usual2970/certimate#200]
**功能描述**
简要描述你希望添加的功能和相关问题。

文档没有说明什么时候给你发通知，也没办法知道知道自己配置的东西是否正确

**动机**
为什么这个功能对项目有帮助？
能验证发送功是否成功配置，而不是随便配了，到时候却不知道有没有配置成功。

**替代方案**
描述你已经考虑过的替代方案。

**其他信息**
在这里添加任何相关的附加信息或截图。
![image](https://github.com/user-attachments/assets/fca5e490-5488-4e1f-a99d-baa8b07c4711)

**Comment by isyueshen** [comment]
加一个测试功能还是挺有用的, 避免配置错误

**Comment by JavaSCU** [comment]
附议

**Comment by xxxit** [comment]
建议+1

**Comment by usual2970** [comment]
已支持 v0.2.5
