### ISSUE TITLE
[Feature] v0.2.0版本通配符域名多个部署还是会生成多个不同的证书

### ISSUE THREAD

**Issue by ginshark** [usual2970/certimate#201]
**功能描述**
希望一个域名的通配符域名可以一张证书 部署到多个服务 而不是 申请多个通配符域名证书 如图所示 希望只有一张*.abc.com的证书
另外 v0.2.0 目前 主域名和通配符域名还是不能申请为一张证书 如abc.com *.abc.com 不能在添加域名的时候写在一起 或者是有什么特殊的分隔符么 测试 逗号 空格都无效
**动机**
一个通配符域名证书 对应多个二级域名部署 方便管理
**替代方案**
无
**其他信息**
![image](https://github.com/user-attachments/assets/c3a4ea1f-6ded-4e5c-b73e-79a0b9d3189c)

**Comment by usual2970** [comment]
![image](https://github.com/user-attachments/assets/d5511fb9-ad32-4c7c-b2f3-2f9873390551)

这 ui 这么难用吗😃

**Comment by liubin95** [comment]
标示不太清晰。第一时间没发想到，可以添加多个😄
