### ISSUE TITLE
[问题] 域名解析指向的服务器需要开放53端口吗？

### ISSUE THREAD

**Issue by xxxit** [usual2970/certimate#202]
<img width="943" alt="image" src="https://github.com/user-attachments/assets/7a37472a-ba74-4809-9436-02c44924552f">

**Comment by zhanglei2602** [comment]
你的域名服务器填写错了，不是填自己的云服务器IP，是填写域名服务商的IP，比如腾讯云是119.29.29.29
182.254.116.116

**Comment by zlzlzhanglong** [comment]
切换版本至0.1.19并重新新增域名可解决

**Comment by usual2970** [comment]
没有必要的话可以不设置的

**Comment by xxxit** [comment]
> 不要填写 域名服务器 字段

  谢谢，已经解决，这应该是个bug，只要在添加域名时，输入了域名服务器，就算后面再删了，或者再添加其他域名都会造成无法申请成功，就会一直报我发的错误，后来将服务重装之后不填写一切正常，@usual2970 作者可以关注一下这个问题，我觉得是个坑，放个域名服务器的框会很容易造成误判。
