### ISSUE TITLE
[Bug] ssh部署授权添加之后无法在DNS 服务商授权配置下拉框中出现

### ISSUE THREAD

**Issue by hahsuu** [usual2970/certimate#205]
**描述问题**
ssh部署授权添加之后无法在DNS 服务商授权配置下拉框中出现

**截图**
如有可能，请添加截图以帮助解释问题。
![image](https://github.com/user-attachments/assets/e8c5a603-b699-4067-b62f-d2fedb17be8f)
![image](https://github.com/user-attachments/assets/0cc23c85-2446-495a-af6e-b660ce87fb4c)

**环境**
- 操作系统: [Windows,]
- 浏览器: [Chrome,]

**Comment by fudiwei** [comment]
这里的 DNS 服务商是用于 ACME 的 DNS-01 认证的，都是云服务商，是签发证书时用的。
SSH 是部署证书的用的，不能用于签发证书。

**Comment by hahsuu** [comment]
您好！
非常感谢您解答。我想问一下，高校的DNS解析大都是自建DNS服务器，并购买收费SSL证书，certimate系统有没有提供上传收费证书，进行批量部署的解决方法。
十分希望能得到您的解答。
谢谢。

usual2970 ***@***.***> 于2024年10月16日周三 13:04写道：

**Comment by usual2970** [comment]
目前不支持，后续有这方面的考虑
