### ISSUE TITLE
[Feature] 希望大佬搞下“百度智能云”的证书部署

### ISSUE THREAD

**Issue by jason1235** [usual2970/certimate#209]
**功能描述**
希望大佬搞下“百度智能云”的证书部署

**其他信息**
相关接口文档：https://cloud.baidu.com/doc/CDN/s/qjzuz2hp8

**Comment by muziqiu2** [comment]
同求，目前在使用百度智能云cdn，并且百度智能云cdn有相关支持接口，希望可以支持

**Comment by usual2970** [comment]
已支持 v0.2.14 感谢 @fudiwei

**Comment by tuoxiansp** [comment]
> 已支持 v0.2.14 感谢 @fudiwei

大佬，我往百度云部署证书遇到了报错，部署失败：failed to execute sdk request 'cdn.PutCert': [Code: DomainConfig.InvalidArgument; Message: the certificate does not match the domain([我的目标域名]); RequestId: 9a753364-3697-4435-8173-66af72f5e818]

下载证书，并用 openssl verify 命令检查，发现 CN=根域名 而非我的目标域名

**Comment by tuoxiansp** [comment]
> > 已支持 v0.2.14 感谢 @fudiwei
> 
> 大佬，我往百度云部署证书遇到了报错，部署失败：failed to execute sdk request 'cdn.PutCert': [Code: DomainConfig.InvalidArgument; Message: the certificate does not match the domain([我的目标域名]); RequestId: 9a753364-3697-4435-8173-66af72f5e818]
> 
> 下载证书，并用 openssl verify 命令检查，发现 CN=根域名 而非我的目标域名

目前版本似乎有一个严重bug，会给所有子域名部署根域名证书，不是百度云这块代码的问题

**Comment by fudiwei** [comment]
> > 大佬，我往百度云部署证书遇到了报错，部署失败：failed to execute sdk request 'cdn.PutCert': [Code: DomainConfig.InvalidArgument; Message: the certificate does not match the domain([我的目标域名]); RequestId: 9a753364-3697-4435-8173-66af72f5e818]
> > 下载证书，并用 openssl verify 命令检查，发现 CN=根域名 而非我的目标域名
> 
> 目前版本似乎有一个严重bug，会给所有子域名部署根域名证书，不是百度云这块代码的问题

BUG 上报请新开一个 Issue，附上详细截图或其他相关信息

**Comment by tuoxiansp** [comment]
> > > 大佬，我往百度云部署证书遇到了报错，部署失败：failed to execute sdk request 'cdn.PutCert': [Code: DomainConfig.InvalidArgument; Message: the certificate does not match the domain([我的目标域名]); RequestId: 9a753364-3697-4435-8173-66af72f5e818]
> > > 下载证书，并用 openssl verify 命令检查，发现 CN=根域名 而非我的目标域名
> > 
> > 
> > 目前版本似乎有一个严重bug，会给所有子域名部署根域名证书，不是百度云这块代码的问题
> 
> BUG 上报请新开一个 Issue，附上详细截图或其他相关信息

刚刚 clone 项目 debug 了，发现是我自己的问题。

很抱歉，是我用法有误，在填写域名的位置填了根域名。
