### ISSUE TITLE
申请同一泛域名支持部署到多个ssh机器上

### ISSUE THREAD

**Issue by HeyKin** [usual2970/certimate#21]
现在使用的是泛域名，测试配置*.t.com后是可生成通用证书的，但我实际应用场景中是多个二级域名分布在不同机器上。

*.t.com只能配置一个。所以看下能不能在增加域名的时候选择多个部署，或允许新增相同域名

**Comment by o2asdv** [comment]
开发者是否考虑，诸如调用shell命令时，将证书路径、文件名等相关信息以环境变量的形式注入进去。这样用户可以通过自定义脚本的形式推送。

**Comment by usual2970** [comment]
@HeyKin @o2asdv 感谢反馈，近期支持

**Comment by HeyKin** [comment]
> @HeyKin @o2asdv 感谢反馈，近期支持

辛苦大大。还有个建议增加host配置，目前是用127.0.0.1可访问，部署在其他机器后，通过nginx负载内网IP访问不到。

**Comment by usual2970** [comment]
已支持 v0.1.6
[域名变量及授权组介绍](https://docs.certimate.me/blog/multi-deployer/)


> 辛苦大大。还有个建议增加host配置，目前是用127.0.0.1可访问，部署在其他机器后，通过nginx负载内网IP访问不到。

可以重提一个 Issue

**Comment by usual2970** [comment]
> 辛苦大大。还有个建议增加host配置，目前是用127.0.0.1可访问，部署在其他机器后，通过nginx负载内网IP访问不到。

./certimate serve --http 0.0.0.0:8090
