### ISSUE TITLE
[Feature] 剩余10天自动续期，感觉时间有点短了，希望可以能自定义的变量

### ISSUE THREAD

**Issue by iqyiqy** [usual2970/certimate#211]
**功能描述**
剩余10天自动续期，感觉时间有点短了，希望可以能自定义。15天，或者20天。

**Comment by iqyiqy** [comment]
域名列表的有效期 90 天，没有意义。
这几天还误解了，以为还有90天到期，原来实际一直没变。
建议改成到期时间减去当前时间，剩余有效天数。

**Comment by qywk99** [comment]
> 域名列表的有效期 90 天，没有意义。 这几天还误解了，以为还有90天到期，奇怪为什么一直没变。 建议改成到期时间减去当前时间，剩余的有效天数。

新版本2.5已经支持了剩余天数了，

**Comment by iqyiqy** [comment]
> > 域名列表的有效期 90 天，没有意义。 这几天还误解了，以为还有90天到期，奇怪为什么一直没变。 建议改成到期时间减去当前时间，剩余的有效天数。
> 
> 新版本2.5已经支持了剩余天数了，

看到了，项目更新的很及时。

**Comment by usual2970** [comment]
感谢反馈～ 后续没有这方面的迭代计划

欢迎提交 PR

**Comment by LuRcX** [comment]
附议，一些云平台提前很久就会通知更换证书，需要自定义时间
