### ISSUE TITLE
[Bug] 一个数据库的问题

### ISSUE THREAD

**Issue by fudiwei** [usual2970/certimate#212]
表 `deployments` 的 `domain` 这列，从字面意思上看应该存储的是“域名”（即表 `domains` 的 `domain` 列），但现在存储的却是“邮箱”（即表 `domains` 的 `email` 列）。

见下图：

![image](https://github.com/user-attachments/assets/33e85d39-c949-4180-96de-81c765ba6f6b)

请问这是故意设计成这样的吗？

**Comment by usual2970** [comment]
这里的 domain 对应的就是 domains

这是 pocketbase 的设计，关系型的字段其实在底层存储的是 id(string)，设置关系的时候没法指定显示哪个字段，pocketbase在渲染列表的时候自动选择了，他认为有意义的字段，比如 name、title。它这里选择了 email。

**Comment by fudiwei** [comment]
明白了，谢谢

**Comment by usual2970** [comment]
![WX20241017-233533](https://github.com/user-attachments/assets/405e938e-7853-41a0-a0c3-0465460b8658)
