### ISSUE TITLE
[Feature] 小白一枚，请问我是安装在笔记本上的，这软件是如何在证书到期前提示我的？

### ISSUE THREAD

**Issue by zhl111** [usual2970/certimate#213]
**功能描述**
我按照说明运行了网页，设置了证书后，就把页面和软件关闭了，我不知道它是如何能提示我证书过期及续约呢？还是说这个功能必须安装在服务器上自动运行才能做到？

不懂编程，多有冒昧……

**Comment by usual2970** [comment]
感谢反馈～ 保持 certimate运行状态，certimate会检查证书状态，并推送过期信息至你配置好的渠道

具体可加群咨询更多信息
