### ISSUE TITLE
[Bug] 删除授权组，提示信息有bug

### ISSUE THREAD

**Issue by withcb** [usual2970/certimate#215]
**描述问题**
授权组下有授权，此时点击删除授权组，实际没有删除，也没有弹出任何信息。

而此时在点击切到「域名列表」，这个时候才弹出了【删除失败】信息

![image](https://github.com/user-attachments/assets/113c131e-7c65-4a10-86f2-2abb09b00d55)

**Comment by usual2970** [comment]
感谢反馈～后续授权组要删除掉，这里可以不用了
