### ISSUE TITLE
[Feature]  希望消息推送增加 bark

### ISSUE THREAD

**Issue by hurole** [usual2970/certimate#219]
**功能描述**
希望消息推送增加 bark

**动机**
个人项目使用bark 还是挺方便的

**替代方案**
描述你已经考虑过的替代方案。

**其他信息**
[github.com/nikoksr/notify](https://github.com/nikoksr/notify/tree/main/service/bark)

**Comment by isyueshen** [comment]
Apprise 也不错, 支持很多发送通道

**Comment by funnyzak** [comment]
提了 PR #294，加入了 Bark 支持
