### ISSUE TITLE
[Bug] 👾 由于 Acme 认证 CNAME 跟随导致认证失败问题

### ISSUE THREAD

**Issue by PBK-B** [usual2970/certimate#228]
**描述问题**
泛解析域名，lego 默认实现启用了签发认证 CNAME 跟随，这会导致出现签发认证失败问题。

相关上游 issue: https://github.com/go-acme/lego/issues/1867

**复现步骤**
复现该问题的步骤：
为 CNAME 解析的泛解析域名签发并部署证书

**期望的结果**
签发成功

**日志**
```
[2024-10-20 23:03:39]
开始检查
[2024-10-20 23:03:39]
获取记录成功
[2024-10-20 23:03:39]
检查通过
[2024-10-20 23:03:39]
开始申请
[2024-10-20 23:03:43]
申请证书失败
error: one or more domains had a problem: [example.com] [example.com] acme: error presenting token: alicloud: zone w.kunlunpi.com. not found in AliDNS for domain all.example.com.w.kunlunpi.com.
```

**环境**
nil

**其他信息**
Onboarding Your Customers with Let's Encrypt and ACME: <https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme/#the-advantages-of-a-cname>

**Comment by PBK-B** [comment]
@usual2970 我这边尝试在添加域名时增加 `DisableFollowCNAME` 参数，用于配置 lego 的 `LEGO_DISABLE_CNAME_SUPPORT` 行为，已测试能够成功签发。

<img width="792" alt="img01" src="https://github.com/user-attachments/assets/8da6165a-df20-4705-a084-0b4c5902e762">

**Comment by usual2970** [comment]
> @usual2970 我这边尝试在添加域名时增加 `DisableFollowCNAME` 参数，用于配置 lego 的 `LEGO_DISABLE_CNAME_SUPPORT` 行为，已测试能够成功签发。

👌👌
