### ISSUE TITLE
[Bug] 证书申请成功了，使用本地部署，但是在部署配置中设定的证书保存路径和私钥保存路径没有出现 .crt与 .key 文件

### ISSUE THREAD

**Issue by wf58585858** [usual2970/certimate#231]
**描述问题**

添加了一个域名，使用本地部署，发起申请证书后证书申请成功了
证书申请成功了，使用本地部署，但是在部署配置中设定的证书保存路径和私钥保存路径没有出现 .crt与 .key 文件

这个文件夹提前创建好了，权限777
/www/wwwroot/certimate/ssl/---.com

申请完以后没出现两个文件
/www/wwwroot/certimate/ssl/---.com/certificate.crt
/www/wwwroot/certimate/ssl/---.com/private.key

[2024-10-21 12:05:14]
开始检查
[2024-10-21 12:05:14]
获取记录成功
[2024-10-21 12:05:14]
检查通过
[2024-10-21 12:05:14]
开始申请
[2024-10-21 12:05:32]
申请证书成功
证书地址: https://acme-v02.api.letsencrypt.org/acme/cert/03378e83ced35b36f609df9f2aaba6dc840---
[2024-10-21 12:05:32]
保存证书成功
[2024-10-21 12:05:32]
开始部署
[2024-10-21 12:05:32]
部署失败
执行前置命令失败: 执行命令失败: exit status 1

**Comment by iqyiqy** [comment]
执行的什么前置命令？
我用的docker，感觉没必要用本地部署，还需要映射路径。
直接和其它机器一样，用ssh连接就行。

**Comment by usual2970** [comment]
感谢反馈～ 这应该还没到证书保存到本地路径那一步，前置命令就失败了

可以加入群聊反馈，有了解的同学会第一时间帮助你

**Comment by wf58585858** [comment]
知道问题了
我写的前置命令是将保存好的证书复制到我指定的位置
原来这个逻辑要写在 命令 那一栏中，不能写在 前置命令 中
