### ISSUE TITLE
希望可以支持群晖NAS的部署

### ISSUE THREAD

**Issue by ninotsui** [usual2970/certimate#232]
群晖NAS一直需要外网访问，但是每个90天就要找个新的免费证书然后在群晖中上传配置好。否则就担心数据泄露，很多厂商90天后就不免费了，每90天就要重新找一个免费的......

**Comment by x2358473** [comment]
你可以暂时先用一下acme.sh。这个支持群晖,使用的是Let's Encrypt 免费的90天ssl

**Comment by ninotsui** [comment]
> 你可以暂时先用一下acme.sh。这个支持群晖,使用的是Let's Encrypt 免费的90天ssl

先跪谢大佬回复
有试，但是因为家里不给开80 所以验证不了。

**Comment by x2358473** [comment]
> > 你可以暂时先用一下acme.sh。这个支持群晖,使用的是Let's Encrypt 免费的90天ssl
> 
> 先跪谢大佬回复 有试，但是因为家里不给开80 所以验证不了。

群晖自带的 Let's Encrypt 才需要80验证。使用acme.sh不需要。你可以在github上搜下acme.sh。百度上也很多自动化部署到群晖的教程

**Comment by zhangziran** [comment]
> 群晖NAS一直需要外网访问，但是每个90天就要找个新的免费证书然后在群晖中上传配置好。否则就担心数据泄露，很多厂商90天后就不免费了，每90天就要重新找一个免费的......

如果是群晖的话，我认为他原本就支持的，你可以选择ssh连接群晖，然后放到对应目录就好了

**Comment by heiyu8** [comment]
群晖可以部署
