### ISSUE TITLE
希望可以支持open-wrt的部署，open-wrt的管理面板一直暴露在外网且没有https.....有点虚

### ISSUE THREAD

**Issue by ninotsui** [usual2970/certimate#233]
**功能描述**
简要描述你希望添加的功能和相关问题，1 个 ISSUE 只描述一个功能。

**动机**
为什么这个功能对项目有帮助？

**替代方案**
描述你已经考虑过的替代方案。

**其他信息**
在这里添加任何相关的附加信息或截图。

**Comment by zhangziran** [comment]
其实openwrt也可以通过ssh支持，如果没有公网可以先用vpn等组个局域网
