### ISSUE TITLE
[Feature] 部署配置支持按配置顺序逐个执行

### ISSUE THREAD

**Issue by JavaSCU** [usual2970/certimate#237]
**功能描述**
在域名的部署配置中，如果存在多个，可以配置执行顺序，系统按顺序逐个执行

**动机**
某些场景下不同位置的证书的更新有先后要求

**替代方案**
无

**其他信息**
无

**Comment by usual2970** [comment]
感谢反馈～虽然不清楚具体什么场景需要按顺序执行，Certimate 目前就是按顺序执行的

**Comment by JavaSCU** [comment]
> 感谢反馈～虽然不清楚具体什么场景需要按顺序执行，Certimate 目前就是按顺序执行的

现版本不能调整顺序，可否考虑支持下多个部署可以在管理界面调整顺序，谢谢
