### ISSUE TITLE
部署到阿里OSS报错

### ISSUE THREAD

**Issue by raofeng** [usual2970/certimate#24]
报错内容：
SDKError: StatusCode: 400 Code: MissingStatus Message: code: 400, Status is mandatory for this action. request id: BD2910A2-EE31-5DA0-BB2D-8290467AA3A5 Data: {"Code":"MissingStatus","HostId":"cas.aliyuncs.com","Message":"Status is mandatory for this action.","Recommend":"https://api.aliyun.com/troubleshoot?q=MissingStatus\u0026product=cas\u0026requestId=BD2910A2-EE31-5DA0-BB2D-8290467AA3A5","RequestId":"BD2910A2-EE31-5DA0-BB2D-8290467AA3A5","statusCode":400}

**Comment by usual2970** [comment]
Duplicate of #17

**Comment by alan16742** [comment]
oss 的 api 是 这两个吗
1. https://help.aliyun.com/zh/ssl-certificate/developer-reference/api-cas-2020-04-07-createdeploymentjob?spm=a2c4g.11186623.0.0.71df46eda7VOlJ
2. https://help.aliyun.com/zh/ssl-certificate/developer-reference/api-cas-2020-04-07-listcloudresources?spm=a2c4g.11186623.0.0.4e8e46edpW6KJm
