### ISSUE TITLE
[Feature] 希望可以支持阿里云、七牛云等cdn的泛域名部署

### ISSUE THREAD

**Issue by zhangziran** [usual2970/certimate#241]
**功能描述**
希望可以支持阿里云、七牛云等cdn的泛域名部署

**动机**
为什么这个功能对项目有帮助？
便于管理

**替代方案**
描述你已经考虑过的替代方案。
替代方案是创建很多个子域名，但这样配置cdn缓存等会非常繁琐。

**Comment by LeoChen98** [comment]
这个可能要自己写feat，比如我自己动手写了腾讯云的feat(

**Comment by zhangziran** [comment]
> 这个可能要自己写feat，比如我自己动手写了腾讯云的feat(

实测腾讯云、华为云泛域名可用，阿里云报错域名不存在，七牛云报错getDomainInfo failed: req failed: ToRequest failed: status code is not 200: 404

**Comment by LeoChen98** [comment]
> > 这个可能要自己写feat，比如我自己动手写了腾讯云的feat(
> 
> 实测腾讯云、华为云泛域名可用，阿里云报错域名不存在，七牛云报错getDomainInfo failed: req failed: ToRequest failed: status code is not 200: 404

所以说让你自己动手写功能啊，开源项目主打一个你觉得不行就自己写代码
