### ISSUE TITLE
[Bug] 证书签发不包含根域名

### ISSUE THREAD

**Issue by zhangziran** [usual2970/certimate#245]
**描述问题**
证书签发不包含根域名，比如我申请*.a.com他就只会申请*.a.com
然后我把a.com和*.a.com一起添加到域名中，他又只会申请a.com（似乎是部署应用的？）

**Comment by zhangziran** [comment]
这个应该也不算是啥bug，设计之初就是考虑一个子域名在域名列表创建一条记录？如果是这样的话，那可能需要增加个搜索功能了。。。。。。

**Comment by usual2970** [comment]
虽然没看到你的具体配置是什么？但是现在是可以包含根域名的
