### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 0ps** [usual2970/certimate#248]
15:08:11 [INFO] acme: Registering account for x@x.com
2024/10/23 15:08:13 [INFO] [11.com] acme: Obtaining bundled SAN certificate
2024/10/23 15:08:13 [INFO] [11.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1
2024/10/23 15:08:13 [INFO] [11.com] acme: Could not find solver for: tls-alpn-01
2024/10/23 15:08:13 [INFO] [11.com] acme: Could not find solver for: http-01
2024/10/23 15:08:13 [INFO] [11.com] acme: use dns-01 solver
2024/10/23 15:08:13 [INFO] [11.com] acme: Preparing to solve DNS-01
2024/10/23 15:08:35 [INFO] [11.com] acme: Cleaning DNS-01 challenge
2024/10/23 15:08:55 [WARN] [11.com] acme: cleaning up failed: tencentcloud: failed to get hosted zone: zone so. not found in dnspod for domain _acme-challenge.11.com.
2024/10/23 15:08:56 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/1

**Comment by usual2970** [comment]
可在 编辑域名 》申请配置 》高级设置里 》禁用 DNS CNAME 跟随
