### ISSUE TITLE
[Feature] 部署www二级域名，自动添加一级域名

### ISSUE THREAD

**Issue by littleyz** [usual2970/certimate#249]
**功能描述**
能否在添加www二级域名时，也自动添加一级域名

**动机**
之前已经在宝塔面板上申请部署过ssl证书了，宝塔的策略是添加www域名时，会默认添加了一级域名（证书的路径唯一）。与本项目的配置有点冲突，本项目www域名，一级域名，泛域名似乎是三种情况，与宝塔的不能兼容。

**替代方案**
无。删掉宝塔的部署，重新申请泛域名，与本项目一致。

**其他信息**
在这里添加任何相关的附加信息或截图。

**Comment by littleyz** [comment]
> 按照这个设置，也不行。 #201

在issues里搜索了下，似乎是这个原因导致的。https://github.com/usual2970/certimate/issues/76

**Comment by usual2970** [comment]
感谢反馈～ 目前已经申请过证书的域名，修改后也不会重新申请，可以删除重配
