### ISSUE TITLE
Why doesn't the key on dnspod work?

### ISSUE THREAD

**Issue by suixhxy** [usual2970/certimate#25]
Hello, why didn't my dnspod key work when I configured it?

![image](https://github.com/user-attachments/assets/9fe0725a-b5ca-4ce3-9029-e6377eb28ca2)

The error message "Key not found," however, my key was obtained on the dnspod backend and is correct.
Please help to answer, thank you!

The complete log error is as follows:

error: one or more domains had a problem: [*.yt.starhaha.com] [*.yt.starhaha.com] acme: error presenting token: tencentcloud: failed to get hosted zone: API call failed: [TencentCloudSDKError] Code=AuthFailure.SecretIdNotFound, Message=SecretId不存在，请输入正确的密钥。, RequestId=499e3993-fb4a-4174-9671-f0faf001

**Comment by usual2970** [comment]
Hello, is your DNSPOD the China site or the international site?

**Comment by usual2970** [comment]
https://cloud.tencent.com/document/product/1427/56192

![image](https://github.com/user-attachments/assets/0e4d6b34-ac6f-4726-b80b-1c7e8e6426c3)

Check if there are any spaces before or after the key.

**Comment by suixhxy** [comment]
First of all, thank you for answering my question. Thank you very much
Yes, it is the DNSPOD of China. It's not international.
Also, you mentioned to check the correctness of the key, I have done the check, it is correct. In addition, I used other tools acme.sh to configure this secret key and apply for a free certificate, which can be successfully applied, so the argument that the secret key is incorrect can be excluded.

**Comment by suixhxy** [comment]
最新的报错日志如下：
![image](https://github.com/user-attachments/assets/1c6886bc-be9b-48b0-b7a9-87b1cef69936)

**Comment by suixhxy** [comment]
The latest error log is as follows:
![image](https://github.com/user-attachments/assets/1a00fa05-44cb-4cff-b38c-a876a9e1ed0c)

**Comment by suixhxy** [comment]
Thank you very much for your answer. After your prompt, I analyzed the log and guessed that the machine where my certimate service was located had suspended the proxy.
After viewing the public IP address:
curl ipinfo.io/ip
If the ip address is indeed the IP address after the proxy, cancel the proxy and re-deploy the certificate. The certificate can be successfully applied for.
Thank you very much, must give you a thumbs up!!!
