### ISSUE TITLE
[Feature] 希望新增对windows server服务器IIS证书支持

### ISSUE THREAD

**Issue by hucanye** [usual2970/certimate#250]
**功能描述**
新增pfx格式证书申请和windows部署支持

**动机**
目前申请和下载及部署都只支持pem格式证书，没有pfx可选，对于windows服务器iis用户无法使用。

**替代方案**
可以考虑增加证书格式多选，同时前期增加支持ftp部署。

**Comment by LeoChen98** [comment]
在做了在做了，但是ftp部署不太现实，安全风险有点高

**Comment by usual2970** [comment]
@hucanye 这个PR可以帮忙做个测试吗，我手边没有windows设备
