### ISSUE TITLE
[Feature] 完善API文档说明

### ISSUE THREAD

**Issue by aazf** [usual2970/certimate#252]
**功能描述**
支持通过api来增加删除域名，部署等，系统本身就是基于API设计的，因此完善相关文档应该可以无缝支持API

**动机**
这样可以和第三方系统对接，无需通过ui来完成证书的管理

**Comment by usual2970** [comment]
有这方面的想法，包括把 Certimate 作为类库向外开放。

不过目前 Certimate 设计上还没有完全定型，后面可能会出个和当前设计不一致的版本，所以这些工作要先置后了。

**Comment by usual2970** [comment]
暂时没有这方面的计划
