### ISSUE TITLE
[Feature] 能否增加对又拍云的支持

### ISSUE THREAD

**Issue by littleyz** [usual2970/certimate#256]
**功能描述**
支持对又拍云的对象存储及CDN的支持
**动机**
又拍云的对象云存储及CDN用户量还是很大的。

**替代方案**
描述你已经考虑过的替代方案。

**其他信息**
又拍云的API地址：https://api.upyun.com/doc#/api/guide/overview/

**Comment by usual2970** [comment]
感谢反馈～又拍云没看到相关接口

**Comment by littleyz** [comment]
> 感谢反馈～又拍云没看到相关接口

你看下，这种采用模拟登陆的方式是否可行。

https://github.com/monkey-wenjun/migrate_upyun_certificate

**Comment by usual2970** [comment]
出于安全方面考虑，不打支持模拟登录的方式

你可以使用webhook的方式部署，自行模拟登录
