### ISSUE TITLE
[Bug] 申请证书失败

### ISSUE THREAD

**Issue by Xiong-qi** [usual2970/certimate#258]
![image](https://github.com/user-attachments/assets/c17c2de3-8c88-463f-9974-4808aba6edeb)

[2024-10-25 15:24:22]
开始检查
[2024-10-25 15:24:22]
获取记录成功
[2024-10-25 15:24:22]
检查通过
[2024-10-25 15:24:22]
开始申请
[2024-10-25 15:24:23]
申请证书失败
get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get "https://acme-v02.api.letsencrypt.org/directory": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by usual2970** [comment]
https://github.com/go-acme/lego/issues/239

和这个是同一个问题，可参考一下

**Comment by Xiong-qi** [comment]
@usual2970 非常感谢，已处理
