### ISSUE TITLE
[Feature] 消息推送支持邮箱

### ISSUE THREAD

**Issue by fcwys** [usual2970/certimate#260]
**功能描述**
希望消息推送支持邮箱

**动机**
习惯了使用邮箱接收推送消息，也方便进行归档查询

**替代方案**
无

**其他信息**
无

**Comment by LeoChen98** [comment]
certimate没有在线服务，配置邮件推送可能会非常麻烦，还需要用户自己准备一个发送邮箱。不过如果你确实需要的话，大家应该会乐见你写一个相关的支持。
