### ISSUE TITLE
[Feature] 支持部署到宝塔

### ISSUE THREAD

**Issue by rong6** [usual2970/certimate#270]
**功能描述**
好久没看这个项目了，更新了挺多的，但天下没有完美的系统，还是有一些小瑕疵。   

目前宝塔站点证书保存在`/www/server/panel/vhost/cert/<domain>`，证书和私钥文件名分别为`fullchain.pem` `privkey.pem`。而我每次申请证书必须手动输入该目录来推送部署，希望可以添加一个部署方式，根据域名自动生成证书、密钥保存路径。   
如有域名`a.com`，在输入SSH信息之后无需手动输入证书、密钥保存路径，而是自动推送至`/www/server/panel/vhost/cert/a.com/fullchain.pem`和`/www/server/panel/vhost/cert/a.com/privkey.pem`，然后宝塔再手动启用证书即可。

不知道宝塔有没有提供对应API，如果有，则可以不使用SSH直接推送，然后自动启用证书（翻了一下宝塔官网好像没有关于启用证书的API，手动抓了一下好像是`/site?action=SetSSL`，但具体怎么使用就不清楚了）。

**动机**
方便宝塔面板启用证书。

**替代方案**
嗯。。。手动输。。。

**其他信息**
无。

**Comment by fcwys** [comment]
这个可以通过面板看接口，之前用python实现过通过接口设置SSL证书，我也提过对应ISSUE #88

**Comment by usual2970** [comment]
感谢反馈～ 后续没有这方面的迭代计划

欢迎提交 PR
