### ISSUE TITLE
[Feature] 希望添加京东云dns的支持

### ISSUE THREAD

**Issue by Lvmoo** [usual2970/certimate#277]
**功能描述**
希望添加京东云dns的支持

**动机**
支持多云厂商会带来更多的使用者

**替代方案**
描述你已经考虑过的替代方案。
certd 使用acme 其支持京东云DNS，这种方法免去了多云厂商的支持。

**其他信息**
京东云sdk
https://github.com/jdcloud-api/jdcloud-sdk-go

**Comment by usual2970** [comment]
感谢反馈～ 后续没有这方面的迭代计划

欢迎提交 PR
