### ISSUE TITLE
[Bug] 域名太长会遮盖，麻烦修复下，仪表盘、授权管理、部署历史 都这样

### ISSUE THREAD

**Issue by gang2113920** [usual2970/certimate#283]
**描述问题**
域名太长会遮盖，麻烦修复下，仪表盘、授权管理、部署历史 都这样
![1730258332016](https://github.com/user-attachments/assets/3ee8798e-8785-4efa-ad15-e907cab4cd0a)

**复现步骤**
复现该问题的步骤：

仪表盘、授权管理、部署历史 都这样

**期望的结果**
修复UI

**截图**
![1730258332016](https://github.com/user-attachments/assets/380f52ed-7cbf-4407-bfd9-93e11024f0e4)

**环境**

- 操作系统: [e.g. 全系统]
- 浏览器: [e.g. Chrome]
- 仓库版本: [e.g. v0.2.7]

**其他信息**
在此处添加关于该问题的任何其他信息。

**Comment by usual2970** [comment]
已支持 v0.2.12
