### ISSUE TITLE
[Feature] 希望支持同域名多证书的支持

### ISSUE THREAD

**Issue by Allenyou1126** [usual2970/certimate#286]
**功能描述**
如题，允许同一个域名申请不同算法的多个证书。

**动机**

目前我主要使用EC-256算法的证书以提高SSL性能，但仍需要保留RSA2048证书配置作为Fallback以实现对少部分不支持EC-256算法客户端的支持。然而，目前一个网站只能选择一种证书算法，而且不能添加域名相同的两个网站，希望能实现该功能。

**Comment by usual2970** [comment]
感谢反馈～目前使用域名作为唯一索引，你可以填写不同的域名：

比如:
www.a.com

www.a.com
www1.a.com

**Comment by Allenyou1126** [comment]
抱歉，目前我使用泛域名证书，需要同时申请申请example.com和`*.example.com`的RSA2048和EC256证书，这样无法满足需求。

**Comment by Allenyou1126** [comment]
是否考虑使用id来区分不同证书？
