### ISSUE TITLE
[Bug] 删除域名后，部署历史页面出错了

### ISSUE THREAD

**Issue by lezhizhe** [usual2970/certimate#289]
**描述问题**
删除域名后，部署历史页面出错了

**复现步骤**
复现该问题的步骤：

1. 域名管理添加了多个域名，测试申请 SSL 证书
2. 后续删除了这些测试域名
3. 多几分钟访问部署历史页面，就报错了

**截图**
<img width="887" alt="image" src="https://github.com/user-attachments/assets/999af1fc-2faa-4a64-8a32-bf44a35275d7">

**环境**

- 操作系统: [e.g. Windows, macOS]
- 浏览器: [e.g. Chrome, Safari]
- 仓库版本: [Certimate v0.2.11]

**其他信息**

非常感谢作者开源的这个项目， 非常实用。

**Comment by usual2970** [comment]
感谢反馈～ 试了一下，没有复现

**Comment by lezhizhe** [comment]
很奇怪，今天又突然正常了
