### ISSUE TITLE
[Bug] 邮箱channel测试失败

### ISSUE THREAD

**Issue by Angus-Lee0603** [usual2970/certimate#293]
**描述问题**
使用QQ邮箱，发送与接收地址与账号填写的都是本人qq邮箱地址，邮件的服务器地址
smtp.qq.com，端口：465 密码是16位授权码，测试失败
**复现步骤**
复现该问题的步骤：
填写相关配置

**期望的结果**
成功

**截图**
![screenshot-1730387481008](https://github.com/user-attachments/assets/e5ea5996-c568-4459-a191-34f0118c4458)

**环境**

- 操作系统: [ Windows,]
- 浏览器: [e.g. Chrome]
- 仓库版本: [e.g. v2.11]

**其他信息**
在此处添加关于该问题的任何其他信息。

**Comment by JiyongShi** [comment]
host: smtp.163.com
port: 25
同样测试失败，报missing port in address，端口处填25或者留空都是一样的错误
看起来像是这个地方的判断问题，https://github.com/usual2970/certimate/blob/a27a9f55a770e9b795d8fb93ebf7632f9d45e17d/internal/notify/mail.go#L46

**Comment by JiyongShi** [comment]
本地代码修改去掉if，始终拼接端口后，missing port in address没了，但是通过smtp.163.com发送邮件时，始终报550 invalid user错误
