### ISSUE TITLE
[Bug] 部署到腾讯云 COS，地域字段提示错误 无法保存

### ISSUE THREAD

**Issue by lezhizhe** [usual2970/certimate#295]
**描述问题**
部署对象是腾讯云 COS，地域字段保存，无法点击保存

**截图**
<img width="560" alt="image" src="https://github.com/user-attachments/assets/2809b205-3c74-4eff-99f6-df671cd6b1fa">

非常感谢开源的这个项目， 很实用

**Comment by usual2970** [comment]
使用最新版
