### ISSUE TITLE
[Bug] 泛域名证书申请总是失败，单独域名申请正常

### ISSUE THREAD

**Issue by lezhizhe** [usual2970/certimate#301]
配置了泛解析域名，申请泛域名证书总是失败。域名解析用的腾讯云。自己用 acm.sh 申请是正常的

最新版本：[v0.2.13](https://github.com/usual2970/certimate/releases)
<img width="967" alt="image" src="https://github.com/user-attachments/assets/7e04a884-a5d0-4320-8efd-4cbc0c408746">

**Comment by usual2970** [comment]
可以自定义 dns 或者关闭 cname 跟随

**Comment by lezhizhe** [comment]
试了关闭 cname 跟随，还是不行
