### ISSUE TITLE
[Bug] 在部署七牛云时，部署失败，日志只提示开始部署

### ISSUE THREAD

**Issue by jianglianwen** [usual2970/certimate#304]
**描述问题**
在部署七牛云时，部署失败，日志只提示开始部署，没有相应的日志

**复现步骤**

**期望的结果**
部署失败时提示相应的错误

**截图**
![部署日志](https://github.com/user-attachments/assets/d154a16f-f6a9-47a0-8d07-6b121e8150c3)
![结果](https://github.com/user-attachments/assets/92b0113f-8d92-42f2-83e2-1cea07f138a6)

**环境**
- 操作系统: [docker]
- 浏览器: [Chrome]
- 仓库版本: [v0.2.14]

**其他信息**

**Comment by usual2970** [comment]
感谢反馈～ 可以提供一下具体的信息

也可以加入群聊讨论

**Comment by jianglianwen** [comment]
刚刚试了下阿里云的域名部署到七牛云的cdn上，依旧是上面的情况并且服务本身的日志没有报错。。。。。
![日志](https://github.com/user-attachments/assets/861054c5-1640-487a-8119-f91016e3978b)

**Comment by jianglianwen** [comment]
@usual2970 @fudiwei

**Comment by jianglianwen** [comment]
然后七牛云那边的具体情况是证书已经完成上传，但是并没有进行替换操作
