### ISSUE TITLE
[Bug] webhook部署中变量未生效

### ISSUE THREAD

**Issue by JavaSCU** [usual2970/certimate#305]
**描述问题**
**复现步骤**
1、授权管理：设置一条webhook调用，在url中引用变量${xxx}
2、域名-部署配置：授权配置引用上述规则，并设置变量
3、webhook调用中url仍然是变量原始状态，未转换

**截图**
![授权管理](https://github.com/user-attachments/assets/8c304945-81cd-4604-9701-623a0e1d231c)
![域名-部署配置](https://github.com/user-attachments/assets/8c0ed820-b35c-4ffc-a12f-1d0a8d0ad895)
![接收到的参数](https://github.com/user-attachments/assets/590268a3-3611-4c6a-a37b-a81b8067ecf5)

**环境**
[v0.2.14]

**Comment by fudiwei** [comment]
@usual2970 应该是设计如此？

参数变量好像已经在 v0.2.0 里被移除了，但这里应该是没删干净。

**Comment by usual2970** [comment]
@JavaSCU 变量是通过 post 请求，请求到你的 webhook 链接
