### ISSUE TITLE
[Bug] 多吉云更新报错：failed to execute sdk request 'cdn.UploadCdnCert': dogecloud api error, code: 400,

### ISSUE THREAD

**Issue by zhheo** [usual2970/certimate#308]
**描述问题**
多吉云更新报错：failed to execute sdk request 'cdn.UploadCdnCert': dogecloud api error, code: 400,msg: 解析失败，请检查证书是否符合标准，请留意是否有多余的空格

<img width="958" alt="image" src="https://github.com/user-attachments/assets/b360c0f3-b017-4620-8830-febe70d17955">

<img width="690" alt="image" src="https://github.com/user-attachments/assets/b77d9ef0-68f1-48a7-8ef4-95e4e38f1641">

**Comment by fudiwei** [comment]
@zhheo 可以帮忙验证一下这个 PR 吗？

我没有 doge 的账号，完全是依照文档实现的，相关流程均未经测试。

**Comment by zhheo** [comment]
我不太会验证pr。。。

**Comment by tuoxiansp** [comment]
你用的是子域名吗，目前版本似乎有一个严重bug，会给所有子域名部署根域名证书

**Comment by tuoxiansp** [comment]
> 你用的是子域名吗，目前版本似乎有一个严重bug，会给所有子域名部署根域名证书

很抱歉，我的说法有误：刚才 clone 了项目 debug 发现是我自己使用方式不对，不是项目的 bug 。

@zhheo

**Comment by zhheo** [comment]
> > 你用的是子域名吗，目前版本似乎有一个严重bug，会给所有子域名部署根域名证书
> 
> 很抱歉，我的说法有误：刚才 clone 了项目 debug 发现是我自己使用方式不对，不是项目的 bug 。
> 
> @zhheo

你有这个问题吗，[2024-11-07 12:00:58]
部署失败
failed to execute sdk request 'cdn.UploadCdnCert': json: cannot unmarshal number into Go struct field UploadCdnCertResponseData.data.id of type string
