### ISSUE TITLE
[Bug] 登录密码忘记了要怎么找回？

### ISSUE THREAD

**Issue by Wulicheng321** [usual2970/certimate#310]
登录密码忘记了要怎么找回？

**Comment by fudiwei** [comment]
SQLite 打开 `/pb_data/data.db`，找到 `_admins` 那张表，`passwordHash` 那列自己重置吧。

可以随便找个 bcrypt 在线生成的工具，迭代次数填 12，生成完以后复制粘贴回去替换。

**Comment by usual2970** [comment]
![image](https://github.com/user-attachments/assets/269711fb-2633-47bd-b86b-b2c5d9433688)

**Comment by Wulicheng321** [comment]
好的谢谢

________________________________
发件人: usual2970 ***@***.***>
发送时间: 2024年11月7日 8:06
收件人: usual2970/certimate ***@***.***>
抄送: mango ***@***.***>; Author ***@***.***>
主题: Re: [usual2970/certimate] [Bug] 登录密码忘记了要怎么找回？ (Issue #310)


image.png (view on web)<https://github.com/user-attachments/assets/269711fb-2633-47bd-b86b-b2c5d9433688>

―

**Comment by muwn** [comment]
> ![image](https://github.com/user-attachments/assets/269711fb-2633-47bd-b86b-b2c5d9433688)

这个指令疑是不存在了

![Image](https://github.com/user-attachments/assets/21fca3f3-f640-4036-b4ea-942f6bb54e27)

**Comment by songhanlin** [comment]
./certimate superuser update 账号 密码
