### ISSUE TITLE
[Bug] 多吉云更新报错：cannot unmarshal number into Go struct field UploadCdnCertResponseData.data.id of type string

### ISSUE THREAD

**Issue by zhheo** [usual2970/certimate#313]
**描述问题**
[2024-11-07 12:00:58]
部署失败
failed to execute sdk request 'cdn.UploadCdnCert': json: cannot unmarshal number into Go struct field UploadCdnCertResponseData.data.id of type string

<img width="958" alt="image" src="https://github.com/user-attachments/assets/a1e7bada-4ce4-477c-9689-9e33a45878d9">

**Comment by usual2970** [comment]
duplicate #308

**Comment by zhheo** [comment]
感谢！已经彻底解决！部署成功
