### ISSUE TITLE
[Feature] 希望增加查看证书功能 证书(PEM格式)&私钥(KEY)

### ISSUE THREAD

**Issue by wxDadadada** [usual2970/certimate#317]
**功能描述**
希望增加查看证书功能 证书(PEM格式)&私钥(KEY)
在有些使用证书的场景 需要手动添加过去 当我在这里统一管理证书的时候 无法快捷查看证书并复制证书(PEM格式)&私钥(KEY)

**Comment by fudiwei** [comment]
感谢反馈，后续迭代会考虑，也欢迎提交 PR
