### ISSUE TITLE
[Bug] 新建一个授权，删除之后无法新建同名授权

### ISSUE THREAD

**Issue by zhuxiaohao** [usual2970/certimate#322]
**描述问题**
新建一个授权，删除无法新建同名授权了

**复现步骤**
复现该问题的步骤：

1. 新建授权，新建一个名称为test的授权
2. 删除test的授权
3. 再次新建名称为test的授权
4. 此时会发现，有Value must be unique. 提示。

**期望的结果**
删除之后能新建同名

**截图**

![1](https://github.com/user-attachments/assets/dfeb4fda-4f47-4a3b-98f1-6c5f983c60bc)
![2](https://github.com/user-attachments/assets/b452ad24-fe51-4062-b93a-75596e00a9f5)

**环境**

- 操作系统: centos7.9
- 浏览器: Chrome
- 仓库版本: 此时此刻的最新版，今天刚部署的

**其他信息**
无

**Comment by fudiwei** [comment]
这是一个已知问题，请暂时使用不同的名称替代。

**Comment by LeoChen98** [comment]
实在不行你就进pocketbase后台直接删数据吧（出问题了概不负责）
