### ISSUE TITLE
自建k8s集群, 证书问题

### ISSUE THREAD

**Issue by lyzklkl** [usual2970/certimate#323]
**描述问题**
自建的集群, 使用的自带证书,提示: 
failed to create k8s client: specifying a root certificates file with the insecure flag is not allowed

**期望的结果**
希望可以不检测证书问题, 或者添加跳过 TLS 按钮。

**截图**
<img width="682" alt="image" src="https://github.com/user-attachments/assets/e47964b0-7c40-4816-befc-b5a4f3487a6b">

**环境**
docker 部署

**Comment by fudiwei** [comment]
这个应该在你的 KubeConfig 里配置
