### ISSUE TITLE
[Bug] 腾讯云负载均衡部署无法保存配置

### ISSUE THREAD

**Issue by xianyue390348** [usual2970/certimate#324]
**描述问题**
配置腾讯云负载均衡部署时候，右下角保存按钮点击没有反映
**复现步骤**
![image](https://github.com/user-attachments/assets/558a7adb-9267-4236-bb84-f4ffbe23d8d7)

**Comment by fudiwei** [comment]
请暂时选择需要填写域名的其他替换方式。后续版本修复。
