### ISSUE TITLE
[Bug] 添加七牛CDN的泛域名部署提示“请输入正确的域名”

### ISSUE THREAD

**Issue by tanshiqi** [usual2970/certimate#330]
**描述问题**
七牛CDN的泛域名格式是点开头的，比如.example.com，并不是*.example.com

**期望的结果**
能够添加泛域名

**截图**
![image](https://github.com/user-attachments/assets/c5695168-c5c3-4944-98ff-db6c6a7aee37)

**Comment by tanshiqi** [comment]
如果添加了*.example.com这样的域名，则提示：
![CleanShot 2024-11-12 at 21 30 28](https://github.com/user-attachments/assets/8561c202-03d0-4b82-9a02-578a34058a96)

**Comment by usual2970** [comment]
感谢反馈～已知问题，后续修复

另外泛域名就是要 *.example.com 的形式
