### ISSUE TITLE
[Bug] 修改申请证书的域名后不触发重新申请证书的逻辑

### ISSUE THREAD

**Issue by LeoChen98** [usual2970/certimate#334]
**描述问题**
如题

**复现步骤**
修改任意已申请证书的域名记录的域名列表

**截图**

**期望的结果**
修改域名后应当触发重新申请证书逻辑确保证书匹配性

**环境**

- 操作系统: ALL
- 浏览器: ALL
- 仓库版本: v0.2.19

**其他信息**
/

**Comment by LeoChen98** [comment]
WIP/Trying

**Comment by fudiwei** [comment]
不改变数据库表结构的情况下应该是办不到的。但真要是改表结构这种 Breaking Changes 就没啥必要了，0.3.x 整个这张表都会被废弃掉了。

**Comment by LeoChen98** [comment]
> 不改变数据库表结构的情况下应该是办不到的。但真要是改表结构这种 Breaking Changes 就没啥必要了，0.3.x 整个这张表都会被废弃掉了。

先试试看咯

**Comment by LeoChen98** [comment]
> 不改变数据库表结构的情况下应该是办不到的。但真要是改表结构这种 Breaking Changes 就没啥必要了，0.3.x 整个这张表都会被废弃掉了。

弄好了，在申请流程里加了个判断
