### ISSUE TITLE
[Feature] 希望能支持从云服务商那边申请证书

### ISSUE THREAD

**Issue by wsy** [usual2970/certimate#338]
**功能描述**
从腾讯云/阿里云申请免费以及收费证书
![image](https://github.com/user-attachments/assets/b43dfff7-5a71-41ce-adfb-999327456e9a)

**动机**
我之前的证书都是腾讯云申请的，由TrustAsia颁发的。
Certimate并不能从腾讯云下载TrustAsia已经发放的证书并部署。而是直接往新的CA提交了一个申请。

**其他信息**
腾讯云相关API文档
https://cloud.tencent.com/document/product/400/41678

**Comment by LeoChen98** [comment]
trustasia的申请速度太慢了，没啥意思。而且申请的原理不一样，支持那俩要改太多东西了

**Comment by fudiwei** [comment]
感谢建议，近期内没有支持非 ACME 证书的计划。如有需要可以自行 Fork。

P.S. 上传自有证书的功能正在规划中。
