### ISSUE TITLE
是否计划支持K8S中 secret证书更新？

### ISSUE THREAD

**Issue by zszeron** [usual2970/certimate#344]
**功能描述**
简要描述你希望添加的功能和相关问题，1 个 ISSUE 只描述一个功能。

**动机**
为什么这个功能对项目有帮助？

**替代方案**
描述你已经考虑过的替代方案。

**其他信息**
在这里添加任何相关的附加信息或截图。

**Comment by fudiwei** [comment]
现在就是支持的
