### ISSUE TITLE
[Bug] 授权管理tab跳转异常

### ISSUE THREAD

**Issue by JiangJamm** [usual2970/certimate#349]
**描述问题**
在授权管理中，若点击过`授权组`-`所有授权`，再切换到`授权`tab无法显示所有授权。

**复现步骤**
复现该问题的步骤：

1. 授权管理页面，切换到授权组tab
2. 点击某个授权组的`所有授权`按钮
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/4d161d19-4a86-436b-84a0-d9783de02e68">

4. 跳转到`授权页面`
5. 点击`授权组`tab
6. 点击`授权`tab
7. 页面展示的不是所有授权
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/5959d21b-3e59-4e61-adfd-bf8bb9d43e9d">

**期望的结果**
点击`授权`tab应该现实所有授权。

**环境**

- 操作系统: MacOS
- 浏览器: Chrome
- 仓库版本: v0.2.21

**Comment by fudiwei** [comment]
感谢反馈。授权组功能已废弃，相关页面后续将删除，此问题不会修复。
