### ISSUE TITLE
[Bug] 首次添加域名，未到过期前10天仍自动更新证书

### ISSUE THREAD

**Issue by 2156yy** [usual2970/certimate#352]
描述问题
在首次添加域名后，未到过期前10天仍自动更新证书

复现步骤
添加新域名

可能引起问题的因素：
1、首次添加的新域名从未部署，未获取证书有效期。
2、域名证书签发服务商与部署服务商不是同一个。

期望的结果
首次添加新域名后，不会在未到期前10天仍自动更新证书。

其他信息
同时提交一个相关功能请求：

功能描述
新增证书签发服务商自定义选择步骤，应该能跟现有的授权管理的服务商复用，实现证书签发服务商自定义。

动机
虽然一般服务商平台都能证书签发，现在默认的证书签发服务商与部署服务商一致的模式也暂时能实现证书更新功能，但是鉴于证书统一管理、平台的免费证书额度、证书类型选择等原因，期望能自定义选择证书签发服务商平台，满足自定义调整的需要。

**Comment by fudiwei** [comment]
没明白问题，方便补充下截图说明问题吗？

---

> 但是鉴于证书统一管理、平台的免费证书额度、证书类型选择等原因，期望能自定义选择证书签发服务商平台，满足自定义调整的需要。

certimate 是基于 ACME 实现的，仅支持接入满符合 ACME 协议的服务商（如 Let's Encrypt、ZeroSSL 等），不存在所谓“免费证书额度”的问题。现在申请时选择的服务商仅仅是用来通过 API 修改你域名的 DNS 解析的，跟签发证书无关。

更多细节可以自行搜索什么是 ACME 协议。

**Comment by 2156yy** [comment]
明白了。 看到部署平台上SSL页面有证书误以为是通过该服务商平台去签发的，没想起来是证书上传后的证书管理。

至于问题，因为已经更新证明，只能模拟当时场景，大致是添加新域名后
![WX20241122-170816](https://github.com/user-attachments/assets/b6a7febb-4e89-46ef-91bd-d2d7027999f4)

该域名当天暂未获取有效期信息，实际上该域名证书有效期剩余二十多天，但是该域名证书是通过部署服务商平台的免费证书功能申请的Digicert Encryption Everywher DV证书，在次日8时自动执行证书检测部署时，自动更新部署了该域名证书，有效信息更新为剩余89天。
![WX20241122-170816](https://github.com/user-attachments/assets/8818feeb-ab27-4ac0-945e-cd8fbb6eed1c)

**Comment by fudiwei** [comment]
> 明白了。 看到部署平台上SSL页面有证书误以为是通过该服务商平台去签发的，没想起来是证书上传后的证书管理。
> 
> 至于问题，因为已经更新证书，只能模拟当时场景，大致是添加新域名后 ![WX20241122-170816](https://private-user-images.githubusercontent.com/23057508/388874900-b6a7febb-4e89-46ef-91bd-d2d7027999f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzIzOTcsIm5iZiI6MTczMjI3MjA5NywicGF0aCI6Ii8yMzA1NzUwOC8zODg4NzQ5MDAtYjZhN2ZlYmItNGU4OS00NmVmLTkxYmQtZDJkNzAyNzk5OWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDEwNDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4Nzk2NGYwODQ3MDIwMjhhMjk5MGMyZDMzYWM1OTQ5NGQxMmZmNDM3ZmQ0ODUxM2NlMWZhMmRkZmQwNWVkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hLD1_xe2ZE5Uy7viXHFSks2EQPrPTyyyPdsFqeIrnsY)
> 
> 该域名当天暂未获取有效期信息，实际上该域名证书有效期剩余二十多天，但是该域名证书是通过部署服务商平台的免费证书功能申请的Digicert Encryption Everywher DV证书，在次日8时自动执行证书检测部署时，自动更新部署了该域名证书，有效信息更新为剩余89天。 ![WX20241122-171250](https://private-user-images.githubusercontent.com/23057508/388879394-4a477e5c-6594-47f1-910c-56bfc5c3de56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzIzOTcsIm5iZiI6MTczMjI3MjA5NywicGF0aCI6Ii8yMzA1NzUwOC8zODg4NzkzOTQtNGE0NzdlNWMtNjU5NC00N2YxLTkxMGMtNTZiZmM1YzNkZTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDEwNDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NjYyZDhiOTk1ZWY5MWI4NTA4Mjg5YzM3OTUyMWQxZWUxYzhkOGY0MTAxOWI0ODQ3MWJjM2U3YzUzY2E1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aKpJipU7GOhnVePXz7raFjFR7kCSl3d3USqBlag-rqw)

certimate 只能管理通过 certimate 签发的证书，无法检测到你线上系统里已有证书的到没到期。
