### ISSUE TITLE
[Help] 总是遇到 SERVFAIL

### ISSUE THREAD

**Issue by sayunchuan** [usual2970/certimate#356]
**描述问题**

使用docker部署，换过0.2.21 - 0.2.22版本，配置也都试着改过了，我是想通过aliyun进行ssl的本地部署，每次都遇到一个问题：

error: one or more domains had a problem: [XX.XX.XX] propagation: time limit exceeded: last error: authoritative nameservers: NS dns15.hichina.com.:53 returned SERVFAIL for _acme-challenge.XX.XX.XX.

我也试过将等待时间设置为10分钟，可以看到aliyun的后台的域名解析已经有了 _acme-challenge.XX.XX.XX 的解析，求帮忙看看这是什么问题？

**Comment by usual2970** [comment]
感谢反馈～ 可以在 域名编辑 》高级设置 》自定义域名服务器，比如 8.8.8.8
