### ISSUE TITLE
[Feature] 希望支持配置子路径访问

### ISSUE THREAD

**Issue by fcwys** [usual2970/certimate#359]
**功能描述**
希望支持配置子路径访问

**动机**
目前使用nginx反代配置子路径比较麻烦，希望能支持自定义访问路径，也便于提高访问入口的安全性。

**替代方案**
无

**其他信息**
无

**Comment by usual2970** [comment]
感谢反馈～后续没有这方面的迭代计划

引入路径会引入不必要的配置，这与 Certimate 拿来即用的风格不符。

你可以：

1. 使用子域名规避这种问题。
2. 或者 fork 仓库，自行修改源码。

**Comment by fudiwei** [comment]
项目的 UI 是基于 vite + react-router 的，资源路径在打包时就已经确定好了，无法在二进制包里提供可配置项。如果有需要你可以以源码形式自行部署。

**Comment by gaoxizhi** [comment]
我基于当前 main 实现了一版子路径访问支持，准备提交 PR。

与 #1026 的主要区别：

1. 不直接把各处资源地址机械修改为 `./`，而是统一根据 `document.baseURI` 和 Vite `BASE_URL` 计算应用基础路径。
2. PocketBase 客户端使用计算后的实际路径，例如 `/certimate/`，自定义 API 和 PocketBase API 使用同一基础路径。
3. 不要求 PocketBase 服务端支持 baseurl。Nginx 在转发时移除子路径前缀，后端仍然运行在 `/`。
4. 不增加环境变量或运行时配置，同一份构建产物同时支持根路径和任意子路径。
5. 已验证根路径和 `/ce/` 下的登录、API、服务商图标、主题图片和工作流模板。

如果维护者接受这个实现方向，我将提交对应 PR。

**Comment by gaoxizhi** [comment]
PR 已提交：#1401

当前实现已经基于最新 `main` 完成，并验证了根路径与 `/ce/` 子路径下的登录、PocketBase API、自定义 API 及各类静态资源。PR 说明中补充了与 #1026 的实现差异和 Nginx 配置示例。

本方案不增加环境变量或 Certimate 运行时配置，后端仍然运行在根路径，由反向代理移除外部子路径前缀。烦请维护者审阅。
