### ISSUE TITLE
[Feature] 希望增加多个子域名的一同证书申请

### ISSUE THREAD

**Issue by liguanglai** [usual2970/certimate#364]
**功能描述**

希望 certimate 支持一次性申请多个子域名的证书，例如：

*.aaaa.com
*.admin.aaaa.com
*.site.aaaa.com
用户可以通过域名填写时同时指定多个子域名，自动完成证书的申请和续期。
生成一个证书文件。

**其他信息**

用acme.sh 更新的时候可以用以下命令多个子域名进行同一证书的申请。：
acme.sh --issue --dns dns_ali -d aaaa.com -d *.aaaa.com -d *.admin.aaaa.com -d *.school.aaaa.com  --force

**Comment by usual2970** [comment]
感谢反馈～ 域名编辑可以添加多个域名的
