### ISSUE TITLE
[Feature] 建议在部署配置界面显示域名

### ISSUE THREAD

**Issue by LuRcX** [usual2970/certimate#368]
**功能描述**
当前部署配置界面仅显示部署服务商名称和授权名称。建议增加显示域名

**动机**
当部署多个域名时便于管理。
例如申请了一个通配符域名，在同一个CDN配置了多个域名，且该CDN仅支持一次配置一个域名。此时，在“部署配置”中就会出现多条完全一样的条目，无法分辨哪个是哪个。
![image](https://github.com/user-attachments/assets/435b0589-2aad-4a55-8894-9cc1a2d1d909)

**替代方案**
当前需要一个个点进去才能看到，较为不便

**其他信息**

**Comment by fudiwei** [comment]
感谢反馈，v0.3.x 中这个界面即将被废弃。
