### ISSUE TITLE
[Bug] 自动给 Certimate 自身添加证书报错

### ISSUE THREAD

**Issue by Bluecatzmv** [usual2970/certimate#374]
**描述问题**
自动给 Certimate 自身添加证书出现报错http: TLS handshake error from xxx: client sent an HTTP request to an HTTPS server.
系统平台在内网环境里，已配置内网的域名解析，已在平台申请到证书且选择本地部署已传到nginx/ssl文件夹中。
若要自动给 Certimate 自身添加证书是否还需要其他操作，目前无法完成
对于平台自身添加证书是否有更详细的描述，手动部署方式也可以

**环境**
- 操作系统: [ linux centos7.9]
- 仓库版本: [v0.2.23]

**Comment by fudiwei** [comment]
可以截个图吗？

**Comment by Bluecatzmv** [comment]
![Uploading f92c018868941864f951bbbd1f699fa.png…]()

**Comment by Bluecatzmv** [comment]
使用 ./certimate  serve  --http 0.0.0.0:8090 启动可以在浏览器访问 http：//域名:端口 可以解析到
 使用./certimate  serve 域名 启动后80、443端口都启用，但是https：//域名、http：//域名 网页不存在

**Comment by usual2970** [comment]
感谢反馈～

正常情况下，你的域名解析到你的服务器 ip , 并且你的服务器开放了 80、443端口，然后执行 ./certimate server yourdomain.com 就可以自动申请证书了。

所以检查一下：
1. 是否解析了
2. 端口是否打开了，有没有被其它程序占用

如果实在解决不了，建议在前面挂一层代理，如 Nginx、Caddy 等

**Comment by Bluecatzmv** [comment]
还是加了nginx代理，自动部署的错误日志信息有些少，目前已正常使用
![ba346758fcc0079c6942649e3b38c5d](https://github.com/user-attachments/assets/c2a4f47e-ef7c-426e-8101-78e271119fb8)
