### ISSUE TITLE
[Bug] 新增域名时 DNS 服务商授权配置 信息没显示

### ISSUE THREAD

**Issue by chuoke** [usual2970/certimate#379]
**描述问题**
新增域名时 `DNS 服务商授权配置` 信息没显示

**复现步骤**
从 main 分支 获取到 docker-compose.yml，直接 docker  compose up -d

1. 去到 '新增域名'
2. 发现DNS无法加载，直接新增能成功，但不会被添加到列表显示
3. 打开 console，发现没问题，已添加的DNS配置接口响应成功

**期望的结果**
可以选择 `DNS 服务商授权配置 `

**截图**
如有可能，请添加截图以帮助解释问题。

**环境**

- 操作系统: [docker]
- 浏览器: [Chrome]
- 仓库版本: [main  registry.cn-shanghai.aliyuncs.com/usual2970/certimate:latest]
- latest 版本是 v0.2.23-beta ，切换到 v0.2.21 ，还是一样

**Comment by usual2970** [comment]
可以提供一下截图吗？

**Comment by chuoke** [comment]
![image](https://github.com/user-attachments/assets/bd0dd3ed-8c87-44cb-aeb8-e149c9a1923a)

其它信息是正常的，由于隐私不便截出

**Comment by fudiwei** [comment]
七牛不是 DNS 服务商。

**Comment by chuoke** [comment]
😂😂😂
