### ISSUE TITLE
[Bug] 自动续期证书服务未工作

### ISSUE THREAD

**Issue by you-hengh** [usual2970/certimate#383]
**描述问题**
如何得知certimate自动续期了证书？我在邮箱看到提示证书快要过期了(12月25日),查看文档说剩余10天的时候会自动续期证书，但是今天17号了，我查看我网站的证书到期时间 仍然没有更新，那么所谓的自动续期服务到底靠谱吗？文档中没有详细的介绍如何部署自动续期服务，是否意味着安装好certimeate 就自动包含了自动续期服务呢?
**复现步骤**
复现该问题的步骤：
无

**期望的结果**
希望自动续期服务正常工作

**截图**
![2024-12-17_23-05-51](https://github.com/user-attachments/assets/50969e84-8803-405e-852a-ca152281c8f0)

**环境**

Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

**其他信息**
服务器为云服务器，通过ssh访问服务器并部署该项目

**Comment by usual2970** [comment]
感谢反馈，建义使用最新的稳定版本
