### ISSUE TITLE
[Bug]  腾讯云 WindowsServer 2012 R2 Datacenter，运行不显示页面

### ISSUE THREAD

**Issue by chenjingchun** [usual2970/certimate#385]
**描述问题**
 WindowsServer 2012 R2 Datacenter 运行不显示页面，win10下是正常的。
日志如下
[logs.zip](https://github.com/user-attachments/files/18191242/logs.zip)

**复现步骤**
复现该问题的步骤：
已安装go1.23.4.windows-amd64_2
使用powershell运行如下图

**期望的结果**
期望正常启动

**截图**
![image](https://github.com/user-attachments/assets/b2c345e1-2c9b-4119-8d0c-51fb11f7f27c)

**环境**
- 操作系统: [e.g. WindowsServer 2012 R2 Datacenter]
- 浏览器: [e.g. Chrome]
- 仓库版本: [e.g. certimate_0.2.23-beta_windows_amd64]

**其他信息**
无

**Comment by fudiwei** [comment]
浏览器版本是？

**Comment by chenjingchun** [comment]
> 浏览器版本是？

Chrome 版本 70.0.3538.110（正式版本） （64 位）

**Comment by fudiwei** [comment]
> Chrome 版本 70.0.3538.110（正式版本） （64 位）

浏览器版本太低了，升级吧。
