### ISSUE TITLE
[Feature] 希望增加name.com平台支持

### ISSUE THREAD

**Issue by xingxingcan** [usual2970/certimate#386]
**功能描述**
Name.com 是一家经 ICANN 认证的域名注册商和网络托管公司，总部位于科罗拉多州丹佛市。自 2003 年成立以来，该公司已发展成为世界领先的域名注册商之一，可提供近 600 个顶级域名。Name.com 在其网站上提供广泛的产品和服务，帮助个人和企业建立并维护成功的在线形象。该公司销售 DNS 域名、虚拟主机、电子邮件服务、SSL 证书和其他网站产品。

**动机**
增加多平台支持，有助于增加项目兼容性。

**替代方案**
无

**其他信息**
https://www.name.com/

**Comment by xingxingcan** [comment]
![image](https://github.com/user-attachments/assets/542812b4-b861-4d29-a8c8-7c4b037963a2)
这是apitoken的样式

**Comment by fudiwei** [comment]
duplicate #78

**Comment by mef777** [comment]
访问失败 permission denied
