### ISSUE TITLE
[Bug] failed to execute sdk request 'cdn.GetDomainInfo': status code is not 200: 404

### ISSUE THREAD

**Issue by JurryFong** [usual2970/certimate#387]
**描述问题**
部署七牛云OSS的时候，证书申请正确，提示failed to execute sdk request 'cdn.GetDomainInfo': status code is not 200: 404报错 

**复现步骤**
点击部署，就提示failed to execute sdk request 'cdn.GetDomainInfo': status code is not 200: 404

![image](https://github.com/user-attachments/assets/e24ee026-b9d9-495a-91d3-7dd61643b8cc)

![image](https://github.com/user-attachments/assets/3663a510-918d-42a2-89a8-9e9293d04108)

**环境**

Docker部署，版本[Certimate v0.2.23-beta](https://github.com/usual2970/certimate/releases)

**Comment by fudiwei** [comment]
七牛控制台的域名和 certimate 部署时填入的域名匹配吗？

**Comment by JurryFong** [comment]
![image](https://github.com/user-attachments/assets/51dac25b-f587-477c-8491-1e6824276575)
![image](https://github.com/user-attachments/assets/80af34e8-a36e-4d9b-b368-08dfa1d1d1f8)
![image](https://github.com/user-attachments/assets/7801cdeb-0441-4ac1-b351-8b539631133f)
![image](https://github.com/user-attachments/assets/8462a958-96c0-48cb-a1da-012e1168b7bd)
上面是我的配置，都是单域名的

**Comment by JurryFong** [comment]
![image](https://github.com/user-attachments/assets/3254a1d1-6360-4a5c-9aec-742735ed110c)
但是我有2条 泛域名的A记录解析，这个照理说是不影响的吧

**Comment by fudiwei** [comment]
certimate 的部署配置方便截个图吗？先关掉启用后再点编辑。

**Comment by JurryFong** [comment]
<img width="869" alt="image" src="https://github.com/user-attachments/assets/77e7308c-00cd-455e-89a7-8a8f2113cb67" />
这个是配置界面

**Comment by fudiwei** [comment]
> <img alt="image" width="869" src="https://private-user-images.githubusercontent.com/35375369/397929751-77e7308c-00cd-455e-89a7-8a8f2113cb67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODc1MzEsIm5iZiI6MTczNDc4NzIzMSwicGF0aCI6Ii8zNTM3NTM2OS8zOTc5Mjk3NTEtNzdlNzMwOGMtMDBjZC00NTVlLTg5YTctOGE4ZjIxMTNjYjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzMjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMmUzZjcwZWFjYmVhZmEyYjJiYWE5MjgzNzhjNzc5Zjk5ZmU2ZmU0N2U1ZjI4MTA0ZGJiMThlNDM5MGFkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UQOWbk_u9Vkeok77NMFHNYM4a7w2s11mtxaqwDzCul4"> 这个是配置界面

部署配置，不是申请配置。

**Comment by JurryFong** [comment]
<img width="581" alt="image" src="https://github.com/user-attachments/assets/25abe916-327c-4f16-8567-1921005a82e9" />

**Comment by JurryFong** [comment]
<img width="656" alt="image" src="https://github.com/user-attachments/assets/d04dad1a-642a-42a5-9050-e0ffa9f2d5b2" />

**Comment by fudiwei** [comment]
![image](https://github.com/user-attachments/assets/b06c6f97-86d1-44d4-97d4-b68df2a220df)

看一下七牛控制台里这个证书 ID 是已经上传了的吗？

**Comment by JurryFong** [comment]
没有上传过去

**Comment by JurryFong** [comment]
我上传截图了，只有一张老的证书

**Comment by fudiwei** [comment]
那我现在怀疑你在 certimate 里填的那组 AK+SK 授权信息不属于你现在登录的七牛账号……所以查不到你这个域名接口才返回 404 的……

因为这个 ID 是七牛 API 返回回来的，它肯定是上传成功了，要不然不会有这个 ID 输出出来，但上传的不是你现在登录控制台的这个账号里。

**Comment by JurryFong** [comment]
我重新生成一个看看

**Comment by fudiwei** [comment]
你看 AK 对不对得上就知道了，七牛控制台里能看到 AK。SK 只有首次生成的时候才显示。

**Comment by JurryFong** [comment]
正如您所说的，是AK和SK错了，搞混掉了，多谢帮助
