### ISSUE TITLE
[Bug] 为什么新增ssh部署的时候，key口令是必填项？

### ISSUE THREAD

**Issue by you-hengh** [usual2970/certimate#388]
**描述问题**
为什么新增ssh部署的时候，key口令是必填项？ #206 

**复现步骤**
复现该问题的步骤：

1. 授权管理 点击列表中的编辑
2. 选择好私钥，点击保存
3. 发现问题

**期望的结果**
我的key在生成的时候就没有设置密码

**截图**
![image](https://github.com/user-attachments/assets/f3093f38-781f-4257-9d83-89ded4ac5939)

**环境**

- 操作系统: Linux
- 浏览器: ssh链接 浏览器edge
- 仓库版本: [v0.2.21]

**其他信息**
我都不知道开发者到底在想什么？ 为什么设置key口令是必填项？到底是什么样的想法？

**Comment by fudiwei** [comment]
随便在输入框里输入点儿什么然后再删掉成空白就好了。

从低版本升级上来的旧授权数据会在某些场景下触发错误的表单验证，只对旧数据首次编辑有影响，新建授权是没有影响的。这是一个已知问题，已计划在 v0.3 时修复。
