### ISSUE TITLE
[Bug] 更新证书不成功，提示applyConfig is empty

### ISSUE THREAD

**Issue by you-hengh** [usual2970/certimate#389]
**描述问题**
我是通过ssh部署证书，但使用certimate后，提示applyConfig is empty
**复现步骤**
复现该问题的步骤：

1. 去到 域名列表
2. 点击 ；列表中项目 选择立即部署
3. 在部署历史中看到日志信息 `applyConfig is empty` 发现问题

**期望的结果**
我只想顺利部署个证书，我不想抱怨，但到目前为止我为了部署证书已经在该项目发了**3个issue**了
#383 , #388 

**截图**
![2024-12-22_14-07-35](https://github.com/user-attachments/assets/4948bd8c-a2a6-4af9-8047-c42d9cc3e7f1)

![2024-12-22_14-15-29](https://github.com/user-attachments/assets/09c71a39-b30d-4dbf-b503-3299cd78e7c0)

**环境**

- 操作系统: linux
- 浏览器: edge
- 仓库版本: [v0.2.21](https://github.com/usual2970/certimate/releases/tag/v0.2.21)

**Comment by fudiwei** [comment]
感谢反馈。目前你所提出的所有 Issue（包括此 Issue），根本原因均来自从 v0.1.x 低版本升级至 v0.2.x 高版本后产生的。

README 中已强调过，[v0.2.0 是一个不向后兼容的版本](https://docs.certimate.me/blog/v0.2.0)。

> ![image](https://github.com/user-attachments/assets/ab3b661d-e074-4ac9-a963-33fb3873b011)

整个 v0.x 期间我们**没有提供平滑升级方案的计划**，大版本升级请自行备份数据后，以**全新部署**的方式升级，而不是直接覆盖旧版本数据库 —— 新旧版本因为数据结构发生很多破坏性变化，直接使用旧版本数据就是会有各种问题。
