### ISSUE TITLE
[Feature] 细节优化

### ISSUE THREAD

**Issue by rong6** [usual2970/certimate#39]
**功能描述**
首先说明，该项目我非常喜欢，找了非常久的SSL证书管理工具，这个是我最满意的一个。当然，项目刚刚起步，还有许多问题，以下是我希望改进的一些功能：
- 支持自定义用户名，而不是只能使用`admin@certimate.fun` （与 #34 相同）
- 支持多用户。
- 支持部署历史删除（强迫症看着部署失败的历史好难受(•́へ•́╬)）。
- 支持证书相关状态推送，例如`证书已续签` `证书即将过期`之类的。

**动机**
优化使用体验。

**替代方案**
无。

**其他信息**
无。

**Comment by usual2970** [comment]
感谢反馈～近期支持
