### ISSUE TITLE
[Bug] 域名列表 => 编辑(新增)域名 => 部署配置的添加form表单无法选择授权配置，且在该form表单下新增的授权配置也无法选择

### ISSUE THREAD

**Issue by coderZoe** [usual2970/certimate#392]
**描述问题**
[Bug] 域名列表 => 编辑(新增)域名 => 部署配置的添加form表单无法选择授权配置

**复现步骤**
点击域名列表，选择编辑/新增域名，配置完成申请配置后点击部署配置，点击新增，选择ssh部署或本地部署，在form表单的授权配置无法选择任何授权配置内容

**期望的结果**
应该能选择已经配置过/新增的授权配置

**截图**
![image](https://github.com/user-attachments/assets/dcbcdcc3-67b2-4cea-8498-d4b6932a1e57)
![image](https://github.com/user-attachments/assets/f249bd1e-8ab4-4b9d-bdf5-576b47e6121f)
![image](https://github.com/user-attachments/assets/0458e94d-b153-4bd0-8d3e-a4da6e4e34ae)
![image](https://github.com/user-attachments/assets/5cd2649c-a6be-4b71-bc91-8faae483f2f9)
![image](https://github.com/user-attachments/assets/e84fe63a-5b82-45a1-b4e7-65c9d4cd142f)
![image](https://github.com/user-attachments/assets/b5e2416c-3d10-43c9-97cc-c713e5ca0576)
![image](https://github.com/user-attachments/assets/ce12abc4-960a-4139-9ceb-37a8699ef3ca)

**环境**

- 操作系统:  Win10
- 浏览器: Edge
- 仓库版本: docker image  usual2970/certimate:v0.2.21和usual2970/certimate:v0.2.23-beta 均有此bug。其他版本未知

**其他信息**
无

**Comment by usual2970** [comment]
你要通过ssh部署到主机上，所以需要填写ssh授权信息，而不是腾讯云授权信息
