### ISSUE TITLE
[Bug] Next分支新UI配置DNS提供商对话框无法正常点击

### ISSUE THREAD

**Issue by RangerCD** [usual2970/certimate#393]
**描述问题**
DNS 提供商配置对话框无法正常工作，输入框和下拉列表不能点击

**复现步骤**
复现该问题的步骤：

1. 去到 '工作流'
2. 点击 '新建工作流'
3. 设置'申请'节点
4. 点击'DNS 提供商授权配置'右侧'新增'
5. 无法点击'授权名称'输入框输入，提供商下拉列表也无法选中

**期望的结果**
可以正常输入名称，可以正常选择提供商

**截图**
![image](https://github.com/user-attachments/assets/3057d02a-a402-4a2c-8704-2f3341a103e6)

**环境**

- 操作系统: Linux 6.11.11
- 浏览器: Chrome 131.0.6778.204 / Firefox 133.0.3
- 仓库版本: v0.3.0-alpha.8

**其他信息**
为了新增DNS提供商，需要在Next分支开发

**Comment by fudiwei** [comment]
这是一个已知问题，流水线相关的 UI 还没有完全适配 antd，后续会调整。

请暂时从授权管理页新增提供商，然后在流水线这里直接选择即可，不要在流水线里新增。
