### ISSUE TITLE
[Bug] 申请证书失败

### ISSUE THREAD

**Issue by QGKevin** [usual2970/certimate#395]
**描述问题**
申请证书失败

**复现步骤**
复现该问题的步骤：

我配置好工作流点击立即执行，过一会提示执行失败日志显示如下：
开始
[2024-12-25 19:17:17]
完成
申请
[2024-12-25 19:17:17]
开始执行
[2024-12-25 19:18:22]
error: one or more domains had a problem: [xx.xxx.com] propagation: time limit exceeded: last error: authoritative nameservers: DNS call error: read udp 10.0.21.2:3967->173.245.58.111:53: i/o timeout [ns=elsa.ns.cloudflare.com.:53, question='_acme-challenge.xx.xxx.com. IN TXT']

以上 xx.xxx.com 是我域名在这我就不显示了

**截图**
![image](https://github.com/user-attachments/assets/f482fe6a-8f0a-4fb9-9227-928a4f4d8f10)
![image](https://github.com/user-attachments/assets/608a92f2-6dd8-425f-b14d-0d792e3cd65c)

**环境**

- 操作系统: Windows
- 浏览器:  Chrome
- 仓库版本: v0.2.23-beta
- 服务器系统centos 7.9
- 使用二进制文件搭建

**Comment by usual2970** [comment]
申请设置里自定义一下dns server

**Comment by QGKevin** [comment]
填写了依旧是失败
