### ISSUE TITLE
前来提建议

### ISSUE THREAD

**Issue by wang4386** [usual2970/certimate#4]
项目很好
与已经开始搞专业版的[certd](https://github.com/certd/certd)功能很像
建议：在程序端申请好证书后，在宿主机运行一键脚本，自动检测宿主机上面的Nginx网站，匹配证书对应域名的网站进行证书自动部署，同样的也应支持docker容器部署的nginx、OpenResty、Tengine等
上述建议灵感来源于[httpsok](https://gitee.com/httpsok/httpsok)

**Comment by usual2970** [comment]
感谢反馈，后续会逐步完善
