### ISSUE TITLE
[Feature] 自定义DNS服务器功能

### ISSUE THREAD

**Issue by o2asdv** [usual2970/certimate#43]
因众所周知的原因，申请增加自定义DNS服务器功能，以防止本地服务器污染。

**Comment by XihongshiFG** [comment]
+1呢，我被这个问题困扰了一上午
N2024/09/18 02:29:11 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
W2024/09/18 02:29:14 [INFO] [xx.xyz] acme: Waiting for DNS record propagation.
W2024/09/18 02:29:18 [INFO] [xx.xyz] acme: Waiting for DNS record propagation.

一直这样然后会最后失败，后来发现是open的dns会缓存记录，等待的2分钟内缓存没更新就失败了，后来指定了母鸡的dns后解决了

**Comment by usual2970** [comment]
已支持 v0.1.8
