### ISSUE TITLE
[Feature] 可否加个强制部署一次因为ssh更改配置后，提示证书在有效期内且已部署，跳过

### ISSUE THREAD

**Issue by XihongshiFG** [usual2970/certimate#44]
**功能描述**
有时候vps重装了系统，变更了密码，证书路径变更了，增加了某些功能命令

发现点立即部署会提示

[2024-09-18 10:34:07]开始检查
[2024-09-18 10:34:07]获取记录成功
[2024-09-18 10:34:07]获取授权信息成功
[2024-09-18 10:34:07]证书在有效期内且已部署，跳过

希望能在部署服务变化过后（本人是ssh部署），ip地址修改，密码更换，路径变化后，能重新上传证书一次证书和执行命令。

另一方面是能在修改部署信息后，实际运行一次，测试流程是不是能跑完，免的三个月后，才发现部署配置有问题

感谢

**Comment by usual2970** [comment]
已支持 v0.1.8
