### ISSUE TITLE
[Document] 请提供“API Token的最小权限列表”以及相关文档

### ISSUE THREAD

**Issue by wsy** [usual2970/certimate#48]
**功能描述**
希望可以完善使用文档。
比如
```markdown
腾讯云 API Token的申请步骤：
1. 创建受限访问的子账户，并勾选xxx权限，
2. ..............
Note:
- 如果DNS和证书都使用腾讯云，则可以采用“自动DNS验证”模式，无需使用API添加TXT记录，所以不需要DNS权限。
```

**动机**
我在尝试添加腾讯云授权
![image](https://github.com/user-attachments/assets/9304be6b-305e-4936-bfa4-ae0ef19076d0)

腾讯云提示我创建受限访问的子账户
![image](https://github.com/user-attachments/assets/c0b68263-eb83-46e8-8c13-4c2e23dcd977)

创建子账户的过程中，需要设置具体权限
![image](https://github.com/user-attachments/assets/a1f15349-022a-4530-aa2d-4885be39d524)

**Comment by usual2970** [comment]
嗯，后续文档可以完善一下

**Comment by Jianfei-DinG** [comment]
> **功能描述** 希望可以完善使用文档。 比如
> 
> ```
> 腾讯云 API Token的申请步骤：
> 1. 创建受限访问的子账户，并勾选xxx权限，
> 2. ..............
> Note:
> - 如果DNS和证书都使用腾讯云，则可以采用“自动DNS验证”模式，无需使用API添加TXT记录，所以不需要DNS权限。
> ```
> 
> **** 我尝试添加腾讯云授权的**动机** ![图像](https://private-user-images.githubusercontent.com/2684991/368633382-9304be6b-305e-4936-bfa4-ae0ef19076d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDM3OTIsIm5iZiI6MTcyNzAwMzQ5MiwicGF0aCI6Ii8yNjg0OTkxLzM2ODYzMzM4Mi05MzA0YmU2Yi0zMDVlLTQ5MzYtYmZhNC1hZTBlZjE5MDc2ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTExMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdhN2NkNmViNWM5OTFkY2NkOTdiMjY5ZDlhYjk0OGMwZmUxYjVkMjlkN2M4OWYzNzAwZjU0NDA1NDRiY2IwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7rCOsUE_9fs4sMyQEbke3lZdtXdamA3PitwBUfJwyPs)
> 
> 腾讯云提示我创建设置访问的子账户 ![图像](https://private-user-images.githubusercontent.com/2684991/368633760-c0b68263-eb83-46e8-8c13-4c2e23dcd977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDM3OTIsIm5iZiI6MTcyNzAwMzQ5MiwicGF0aCI6Ii8yNjg0OTkxLzM2ODYzMzc2MC1jMGI2ODI2My1lYjgzLTQ2ZTgtOGMxMy00YzJlMjNkY2Q5NzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTExMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDljZjgxOTNlYjZiZjBlMmVhMDA4YmQ5YWVlZGRiZjc1NWQyZDhmZjQyYTQ3OTY3MGJjOWRmZTA1NTAwZjIzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S3fyoo-3M7RvCig04QuvruPtZObo5L3AkDR79E5OBqM)
> 
> 创建子账户的过程中，需要设置具体权限 ![图像](https://private-user-images.githubusercontent.com/2684991/368634175-a1f15349-022a-4530-aa2d-4885be39d524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDM3OTIsIm5iZiI6MTcyNzAwMzQ5MiwicGF0aCI6Ii8yNjg0OTkxLzM2ODYzNDE3NS1hMWYxNTM0OS0wMjJhLTQ1MzAtYWEyZC00ODg1YmUzOWQ1MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTExMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYyNzk5ZWM3ZTQ3MTliODE2YjgyMjc5ZmIzNzkzNzRjNTdhMjBjYTAzYzJhYWMyYjdhMDU2YzNiNjQ1MGE4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._sbY-pmRx-tuFQCd6XFSFvOYYz8cDAPD_aS8d9rCuKg)

腾讯的不能用了  能出个阿里的 教程吗

**Comment by LeoChen98** [comment]
> > **功能描述** 希望可以完善使用文档。 比如
> > ```
> > 腾讯云 API Token的申请步骤：
> > 1. 创建受限访问的子账户，并勾选xxx权限，
> > 2. ..............
> > Note:
> > - 如果DNS和证书都使用腾讯云，则可以采用“自动DNS验证”模式，无需使用API添加TXT记录，所以不需要DNS权限。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **** 我尝试添加腾讯云授权的**动机** ![图像](https://private-user-images.githubusercontent.com/2684991/368633382-9304be6b-305e-4936-bfa4-ae0ef19076d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDM3OTIsIm5iZiI6MTcyNzAwMzQ5MiwicGF0aCI6Ii8yNjg0OTkxLzM2ODYzMzM4Mi05MzA0YmU2Yi0zMDVlLTQ5MzYtYmZhNC1hZTBlZjE5MDc2ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTExMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdhN2NkNmViNWM5OTFkY2NkOTdiMjY5ZDlhYjk0OGMwZmUxYjVkMjlkN2M4OWYzNzAwZjU0NDA1NDRiY2IwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7rCOsUE_9fs4sMyQEbke3lZdtXdamA3PitwBUfJwyPs)
> > 腾讯云提示我创建设置访问的子账户 ![图像](https://private-user-images.githubusercontent.com/2684991/368633760-c0b68263-eb83-46e8-8c13-4c2e23dcd977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDM3OTIsIm5iZiI6MTcyNzAwMzQ5MiwicGF0aCI6Ii8yNjg0OTkxLzM2ODYzMzc2MC1jMGI2ODI2My1lYjgzLTQ2ZTgtOGMxMy00YzJlMjNkY2Q5NzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTExMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDljZjgxOTNlYjZiZjBlMmVhMDA4YmQ5YWVlZGRiZjc1NWQyZDhmZjQyYTQ3OTY3MGJjOWRmZTA1NTAwZjIzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S3fyoo-3M7RvCig04QuvruPtZObo5L3AkDR79E5OBqM)
> > 创建子账户的过程中，需要设置具体权限 ![图像](https://private-user-images.githubusercontent.com/2684991/368634175-a1f15349-022a-4530-aa2d-4885be39d524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDM3OTIsIm5iZiI6MTcyNzAwMzQ5MiwicGF0aCI6Ii8yNjg0OTkxLzM2ODYzNDE3NS1hMWYxNTM0OS0wMjJhLTQ1MzAtYWEyZC00ODg1YmUzOWQ1MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTExMTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYyNzk5ZWM3ZTQ3MTliODE2YjgyMjc5ZmIzNzkzNzRjNTdhMjBjYTAzYzJhYWMyYjdhMDU2YzNiNjQ1MGE4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._sbY-pmRx-tuFQCd6XFSFvOYYz8cDAPD_aS8d9rCuKg)
> 
> 腾讯的不能用了 能出个阿里的 教程吗

腾讯的要用最新的版本 https://github.com/usual2970/certimate/releases/tag/v0.1.10 ，我这里跑着没啥大毛病

**Comment by LeoChen98** [comment]
腾讯云目前找到的最小策略集如下图（如果我没有漏掉更加细分的策略的话）：
![image](https://github.com/user-attachments/assets/57f86d54-3b77-4235-9501-132ac7f9cec3)
