### ISSUE TITLE
提建议

### ISSUE THREAD

**Issue by qcmoke** [usual2970/certimate#5]
希望可以支持 letsencrypt、zerossl 等基于 acme 的证书

**Comment by usual2970** [comment]
感谢反馈，目前支持letsencrypt，后续会考虑增加更多选择的

**Comment by qcmoke** [comment]
> 感谢反馈，目前支持letsencrypt，后续会考虑增加更多选择的

没看 letsencrypt 选项啊，这个怎么支持？

**Comment by usual2970** [comment]
可能是我没说清楚，目前仅支持letsencrypt，所以不需要选择选项，默认就是letsencrypt

**Comment by qcmoke** [comment]
> 可能是我没说清楚，目前仅支持letsencrypt，所以不需要选择选项，默认就是letsencrypt
可是授权配置是必选的，无法默认使用letsencrypt添加域名

![image](https://github.com/user-attachments/assets/7483e618-a151-4f80-ba24-137393353424)

**Comment by usual2970** [comment]
DNS服务商授权配置指的是：你域名注册商的授权配置，用来证明域名是你的。

假如你在阿里云注册的域名，就填阿里云授权配置。腾讯云依此类推。当然还有其他很多的云，后续会逐个对接。
