### ISSUE TITLE
[Authentication] 请支持从ActiveDirectory证书服务（AD CS）申请证书

### ISSUE THREAD

**Issue by wsy** [usual2970/certimate#50]
**功能描述**
从Active Directory中申请证书

**动机**
我有一台Windows Server机器（例：winserver.example.com），运行于Active Directory域（例：example.com）环境中。服务器上运行IIS服务。
域中有自建的CA服务器。（例：ca.example.com）

**现有的证书申请过程**
![image](https://github.com/user-attachments/assets/e4e1b686-58c5-43fc-96db-b89923486c03)

**Comment by usual2970** [comment]
感谢反馈～这种场景用户较少，实现性价比低，近期不打算支持

有解决方案，欢迎提 PR
