### ISSUE TITLE
没看到有泛域名的选项。请问泛域名如何设置，在域名里输入多输入几个？

### ISSUE THREAD

**Issue by o2asdv** [usual2970/certimate#51]
没看到有泛域名的选项。请问泛域名如何设置，在域名里输入多个，比如a.com,*.a.com?

_Originally posted by @o2asdv in https://github.com/usual2970/certimate/issues/18#issuecomment-2355270927_

**Comment by usual2970** [comment]
输入*.a.com 就行了，v0.1.8
