### ISSUE TITLE
架构改进

### ISSUE THREAD

**Issue by rookie-man-fack** [usual2970/certimate#53]
加了一个aws的功能部署和证书请求,很符合我现在的需求,非常感谢作者.
我已经改成了zerossl收费证书部署,不限频率和证书个数
我自己感觉Fiber+sqlite+echo 以后项目扩展很麻烦,开发中migrate 数据也不爽,如果可以的话建议gin+mysql, 这只是我的一点建议,你完全可以忽略.反正我的需求是达到了
<img width="974" alt="image" src="https://github.com/user-attachments/assets/96e484e6-4890-4260-8359-0e27216a46c0">
<img width="835" alt="image" src="https://github.com/user-attachments/assets/de11fe87-9d13-48ec-bcbc-0e2fc06d47bf">

**Comment by usual2970** [comment]
好的～感谢建议。

关于扩展的问题，作为运维工具类的项目，扩展应该不是需要首要考虑的问题，除非以后做成 saas（没这个打算） 提供给用户。对于大多数的查询，sqlite 的性能是优于mysql 的。

另外，可以考虑把 aws 的支持提交个 PR，这样你也是这个项目的参与者了🐶🐶

**Comment by rookie-man-fack** [comment]
我就是运维啊,就是因为是运维用,很多基础设施是弹性部署可回收,sqlite有点危险,容器化部署还要做持久化.
可以可以,我再改一下,加个配置文件,到时候同时支持let's 和zerossl, 另外ssh 部署这里还需要改进,一个部署组下应该添加多个服务器ip地址和端口的.

**Comment by usual2970** [comment]
好的～感谢支持

我这也是不了解你们的提需求的原始动机。提需求的时候说一下使用场景，我就明白了。😀

**Comment by rookie-man-fack** [comment]
<img width="573" alt="image" src="https://github.com/user-attachments/assets/780cd2c9-31ff-4043-8200-afaa95ccea8c">
一个ssh部署支持多个主机,大批量部署的情况下,可能就IP不同,证书和用户名都一样,这样就不用多次新建ssh部署了

**Comment by rookie-man-fack** [comment]
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/058fd298-9a62-4cf5-a81b-af86e267887b">
zerossl 也没问题,前端页面你那边估计要做个lets 和zerossl的选项, zerossl 要填ZeroSSL Kid 和ZeroSSL HMAC Key  我这里测试暂时写死的,pocketbase这个包是真难用.

**Comment by usual2970** [comment]
> <img alt="image" width="573" src="https://private-user-images.githubusercontent.com/110986345/369064026-780cd2c9-31ff-4043-8200-afaa95ccea8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTAxMTksIm5iZiI6MTcyNjc4OTgxOSwicGF0aCI6Ii8xMTA5ODYzNDUvMzY5MDY0MDI2LTc4MGNkMmM5LTMxZmYtNDA0My04MjAwLWFmYWE5NWNjZWE4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQyMzUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTIxZWQwZmJjZWU4NDdlZWY4OGI3Y2M0NjMwNzhlZWY0ZWVlNjM0YmJjNTI4NzkyODJmZmZjODU3MDdjODRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NPr70mNvuSNCrChTcJWVMQkiOk7FPAqqQ4CtTvaF-KQ"> 一个ssh部署支持多个主机,大批量部署的情况下,可能就IP不同,证书和用户名都一样,这样就不用多次新建ssh部署了

🎉🎉 我就没考虑到这种情况

**Comment by usual2970** [comment]
> <img alt="image" width="1068" src="https://private-user-images.githubusercontent.com/110986345/369064841-058fd298-9a62-4cf5-a81b-af86e267887b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTAxMTksIm5iZiI6MTcyNjc4OTgxOSwicGF0aCI6Ii8xMTA5ODYzNDUvMzY5MDY0ODQxLTA1OGZkMjk4LTlhNjItNGNmNS1hODFiLWFmODZlMjY3ODg3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQyMzUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjc5ZmFiZGEwZGQxNWZhZWJjODYyNTI5OTYyNTA3MWIwMjU4MTlmOTZiZTdkNWQ4MjNiODk3YjlmNTVhOGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7RS4qED16gwswgOs6DNBgS394YcHaEuKVVUZklSvPFg"> zerossl 也没问题,前端页面你那边估计要做个lets 和zerossl的选项, zerossl 要填ZeroSSL Kid 和ZeroSSL HMAC Key 我这里测试暂时写死的,pocketbase这个包是真难用.

细节我来处理好了

**Comment by rookie-man-fack** [comment]
我还是建议换一个框架,不然后期功能越加越多,目前框架很难扩展了..
1 比如业务需求,我现在要申请IP证书,走http认证签发,你那边扩展就很麻烦. 如果能支持IP证书,又是一个卖点,现在开源产品都不支持IP证书.
2 另外和现有业务的集成回调也不好处理. 比如我现在有一套监控,监控来调用certimate api 来完成申请流程,由用户决定什么时候更新证书.现在的定时任务太简单了.
3 自定义ssl 厂商你那边扩展就更麻烦了,provider都不好加
4 如果后期要添加证书到期各种平台的通知

**Comment by usual2970** [comment]
好的~换架构可以考虑的

用这套主要理由是：

只需要写少量的后端代码，就可以给前端提供接口了，减少了我自己的工作量的同时，可以快速交付功能。

缺点就是：编译出来的包太大了，现在就有60多M了，当然这点要能也无关紧要了。

可以加入微信群组详聊😀
