### ISSUE TITLE
[Feature] 能否支持多域名申请一个证书

### ISSUE THREAD

**Issue by 1066837659** [usual2970/certimate#56]
同一站点需要多个域名

**Comment by usual2970** [comment]
感谢反馈～多个顶级域名吗，暂不支持，后续可以添加

目前可以通过添加多个域名来实现

可以加入到社区来，提供更多细节

**Comment by sgpublic** [comment]
@usual2970 我也是这个需求，具体的，假设二级域名为example.com，我需要申请：

+ example.com
+ *.example.com
+ *.mirrors.example.com

三个域名到一个证书里。

**Comment by usual2970** [comment]
@sgpublic 
目前申请*.example.com会自动申请 example.com的证书，且*.example.com 和example.com共用一张证书

*.mirrors.example.com 单独申请一张就好了

**Comment by sgpublic** [comment]
> *.mirrors.example.com 单独申请一张就好了

还是得申请两个证书啊，也行，那我就等我提的 feat 上线了就迁移到 certimate，感谢佬

**Comment by usual2970** [comment]
感谢反馈～ 可使用 v0.2.0

注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改
