### ISSUE TITLE
[Feature] 能否支持部署到多个ssh服务器

### ISSUE THREAD

**Issue by xtjun** [usual2970/certimate#62]
**功能描述**
一个域名证书部署到多个ssh服务器

**动机**
内外网访问不同服务器、IPV4\V6访问不同的服务器，证书需要复制

**替代方案**
域名创建两项，生成不同的证书部署

**其他信息**
暂无

**Comment by usual2970** [comment]
https://docs.certimate.me/blog/multi-deployer/
