### ISSUE TITLE
[bug] 控制面板状态图标容易混淆

### ISSUE THREAD

**Issue by LTK3** [usual2970/certimate#63]
1. 证书在有效期内 跳过部署 在状态栏图标会显示错误状态. 个人理解这是预期行为 不知道是否有其他含意
2. 日志信息无法清空

**Comment by usual2970** [comment]
好的，感谢反馈~近期优化

欢迎加入群组反馈更多细节

**Comment by usual2970** [comment]
已优化展示问题v0.1.10

日志删除下个版本支持
