### ISSUE TITLE
[建议]能否不要强制要求部署？

### ISSUE THREAD

**Issue by MoeMelon** [usual2970/certimate#64]
因为只是单纯的想要一个可视化自动申请SSL的服务，证书我可以自行下载去部署。

另外已添加的域名似乎不能删除？

**Comment by usual2970** [comment]
感谢反馈~可以考虑

目前可以配置个假的部署，达到这个目的

**Comment by hansedong** [comment]
我也有类似需求，只是想让当前的项目提供证书管理，包括证书申请和证书下载。
目的是希望这个部署操作不与具体云厂商绑定，小厂家 VPS 可以直接调用当前项目的下载接口获取证书。

**Comment by nuo010** [comment]
我也是想要这个功能, 不要强制部署

**Comment by usual2970** [comment]
感谢反馈～ 可使用 v0.2.0

注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改
