### ISSUE TITLE
[Feature] English

### ISSUE THREAD

**Issue by ToshY** [usual2970/certimate#67]
Hello 👋 

I've setup the application with docker compose, but after logging in I have no idea where to start, because well... I don't know Chinese 😅

Is there any chance to have the documentation and application in English (with language toggle or something similar) so other (international) users can try out this tool as well? I understand that it might take a while, but it would be very much appreciated 🙂

**Comment by usual2970** [comment]
Thanks for your feedback! We don’t have an English version at the moment, but it’s something we’re considering. We’ll keep you updated once there’s any progress! Appreciate your patience 😊

**Comment by alvarofpp** [comment]
One suggestion is that we're about to start [Hacktoberfest](https://hacktoberfest.com/), so something you could do is open an issue with the tag `hacktoberfest` to translate into English.

It would be great if you already enabled multiple languages, so I could contribute to both English and Brazilian Portuguese.

**Comment by adozhao** [comment]
歪果仁，不会中文找谷歌翻译~

**Comment by usual2970** [comment]
@alvarofpp 

Thank you for your suggestion, I’ll give it a try.
