### ISSUE TITLE
[Bug] 腾讯云部署证书失败

### ISSUE THREAD

**Issue by LeoChen98** [usual2970/certimate#71]
**描述问题**
将证书部署到腾讯云过程中出现找不到资源的错误

**复现步骤**
复现该问题的步骤：
1. 新建域名
2. 立即部署

**期望的结果**
部署成功

**截图**
![image](https://github.com/user-attachments/assets/6a61de48-6d89-43db-84b1-e242919485d0)

**环境**
- 操作系统: Windows Server 2012 r2
- 浏览器: Chrome@104
- 仓库版本: v0.1.9

**其他信息**
对应apikey的访问记录里没有记录，是否存在api变动？

**Comment by LeoChen98** [comment]
附api访问记录
![image](https://github.com/user-attachments/assets/b9a9e50c-4496-47d0-a687-c36767492c25)

**Comment by lexmin0412** [comment]
Same Problem.

**Comment by usual2970** [comment]
@LeoChen98 @lexmin0412 

https://console.cloud.tencent.com/api/explorer?Product=tag&Version=2018-08-13&Action=GetResources

调试一下看看有没有你们的域名

**Comment by usual2970** [comment]
![image](https://github.com/user-attachments/assets/dd2590c1-615e-43c3-a2a2-ab802847a724)
或者后台看看有没有

**Comment by LeoChen98** [comment]
> @LeoChen98 @lexmin0412
> 
> https://console.cloud.tencent.com/api/explorer?Product=tag&Version=2018-08-13&Action=GetResources
> 
> 调试一下看看有没有你们的域名

有的

**Comment by LeoChen98** [comment]
> ![image](https://private-user-images.githubusercontent.com/1818414/369681358-dd2590c1-615e-43c3-a2a2-ab802847a724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDE5OTcsIm5iZiI6MTcyNzAwMTY5NywicGF0aCI6Ii8xODE4NDE0LzM2OTY4MTM1OC1kZDI1OTBjMS02MTVlLTQzYzMtYTJhMi1hYjgwMjg0N2E3MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTA0MTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWI1MzRiZmY2NjAxMzkxMDU5ZjkxMGI1YTI2ZDg5NGNjZmUxMmZhNjRhOGVlZmI5YjM3YTk5ZjUzOWEzMTI1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HbJbZHQOlTvWvqmXMUSGuCp6pUJpGT28CCvctBXAask) 或者后台看看有没有

这里也有

**Comment by usual2970** [comment]
具体加入群组聊吧，这里沟通效率太低

**Comment by LeoChen98** [comment]
> @LeoChen98 @lexmin0412
> 
> https://console.cloud.tencent.com/api/explorer?Product=tag&Version=2018-08-13&Action=GetResources
> 
> 调试一下看看有没有你们的域名

这个接口是要求一定要给资源打tag吗？如果是的话我可能知道问题出在哪了

**Comment by LeoChen98** [comment]
目前找到的主要问题应该是  上传证书不成功 和 GetResource返回本身不完整

**Comment by usual2970** [comment]
已解决v0.1.10
