### ISSUE TITLE
[Feature] SSH 部署支持部署前执行脚本

### ISSUE THREAD

**Issue by sgpublic** [usual2970/certimate#72]
首先感谢大佬作出的如此好用的项目。

我这边是需要将我的证书部署到一个嵌入式设备上，这个嵌入式设备使用TF卡作为存储设备，因此日常使用的时候是开启的系统分区 readonly，那么如果想要上传证书，需要先使用命令切换为 read/write 才能上传，上传完还要切换回 readonly。

所以需求就是连接 ssh 之后上传证书之前需要执行前置命令。

希望大佬考虑一下这个需求，谢谢。

**Comment by usual2970** [comment]
感谢反馈~这个可以的

只不过ssh部署的界面越来越丑了
