### ISSUE TITLE
[Feature] 申请一个顶级域名的泛域名ssl，如何部署到同一个服务器的多个二级域名网址中？

### ISSUE THREAD

**Issue by wf58585858** [usual2970/certimate#73]
**功能描述**
宝塔中有多个网站,分别使用的同一个顶级域名的不同二级域名,这样的话在certimate域名列表中添加一个顶级域名,每次申请以后自动部署到所有对应的二级域名网站下,能实现吗?

**Comment by usual2970** [comment]
同一个服务器的话，你可以cp到不同的路径，执行自定义的命令就解决了
