### ISSUE TITLE
[Bug] LXC里运行二进制无法打开管理页面

### ISSUE THREAD

**Issue by Omoinemie** [usual2970/certimate#75]
目前二进制运行，启动后打不开网页。

![image](https://github.com/user-attachments/assets/113d5108-d33a-42ee-bcad-8315e69ccc53)

**Comment by usual2970** [comment]
Certimate 默认监听的127.0.0.1:8090 可以执行 `./certimate server --http 0.0.0.0:8090`

你描述的太简单了，我不确定是不是这个原因

**Comment by Omoinemie** [comment]
就是这个问题，你这命令可以解决，建议写到用户手册里面

**Comment by blizzardster** [comment]
> ./certimate server --http 0.0.0.0:8090
你好：多了一个r
./certimate serve --http 0.0.0.0:8090
你这命令可以解决，建议写到用户手册里面，我的是云服务器，不用这个无法远程访问
