### ISSUE TITLE
[Bug] 修改域名后不会重新申请证书

### ISSUE THREAD

**Issue by allegrox** [usual2970/certimate#76]
**描述问题**
修改域名后不会重新申请证书

**复现步骤**
新加域名abc.com，成功申请到证书
修改域名为*.abc.com，即统配证书申请，启动后没有重新执行申请动作

**期望的结果**
域名变化，应该重新执行申请过程

**Comment by sgpublic** [comment]
引用在另一个 issue 里的回复：https://github.com/usual2970/certimate/issues/56#issuecomment-2366750172

**Comment by hurole** [comment]
遇到过

**Comment by usual2970** [comment]
感谢反馈～ 设计如此，可删除重配
