### ISSUE TITLE
希望可以增加手动解析dns验证选项

### ISSUE THREAD

**Issue by ivoidcat** [usual2970/certimate#8]
希望可以增加手动解析dns验证选项，因为部分小众的域名商里面没有

**Comment by usual2970** [comment]
> 希望可以增加手动解析dns验证选项，因为部分小众的域名商里面没有

感谢反馈，可以考虑把域名转移到大众的域名商，解决此问题~

暂时不考虑手动解析，手动解析和系统自动化流程有冲突。
