### ISSUE TITLE
[Feature] 阿里云CDN部署支持通配域名

### ISSUE THREAD

**Issue by callmefool** [usual2970/certimate#80]
**功能描述**
我们阿里云的 CDN、DCDN 有很多域名（img1.example.com、img2.example.com、...），它们都属于同一个二级域名（example.com）。
我在申请证书时，填写的通配域名（*.example.com），证书申请成功，但是在部署时返回了 404 错误。
希望能够支持部署通配域名。

**Comment by usual2970** [comment]
感谢反馈～ 可使用 v0.2.0

注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改

**Comment by callmefool** [comment]
> 感谢反馈～ 可使用 v0.2.0
> 
> 注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改

使用最新版，申请通配证书（*.example.com）成功，部署到阿里云DCDN（域名：a.example.com、b.example.com、...）失败，依然提示 404
![image](https://github.com/user-attachments/assets/f593a85d-2271-42b1-a5e7-e137d88a6d90)

**Comment by usual2970** [comment]
部署配置怎么填的呢

**Comment by callmefool** [comment]
> 部署配置怎么填的呢

![image](https://github.com/user-attachments/assets/714dce63-734f-45f1-9913-0af7fafa78c0)
权限没有问题

**Comment by usual2970** [comment]
部署到域名：填具体的域名，比如 a.example.com ,不要填泛域名

如果有多个，就添加多个部署就行了

**Comment by callmefool** [comment]
> 部署到域名：填具体的域名，比如 a.example.com ,不要填泛域名
> 
> 如果有多个，就添加多个部署就行了

好嘞感谢
