### ISSUE TITLE
[Feature] cf 托管的域名证书申请，希望增大TXT 记录检查时间

### ISSUE THREAD

**Issue by Tomleolt** [usual2970/certimate#82]
**功能描述**
cf 托管域名的证书申请，希望增大TXT 记录检查时间，目前是2min，申请很多次都检测不到，导致申请失败。

**动机**
为什么这个功能对项目有帮助？

**替代方案**
希望可以加个配置，放到环境变量，控制下TXT record 检测时间
应该在cloudflare.go  中
**其他信息**

certimate_server | 2024/09/23 06:19:21 [INFO] [xxx.com] acme: Checking DNS record propagation. [nameservers=8.8.8.8:53,8.8.4.4:53]
certimate_server | 2024/09/23 06:19:23 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
certimate_server | 2024/09/23 06:19:33 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:19:45 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:19:57 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:20:09 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:20:21 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:20:33 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:20:45 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:20:57 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:21:09 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:21:21 [INFO] [xxx.com] acme: Waiting for DNS record propagation.
certimate_server | 2024/09/23 06:21:23 [INFO] [*.xxx.com] acme: Cleaning DNS-01 challenge
certimate_server | 2024/09/23 06:21:24 [INFO] [xxx.com] acme: Cleaning DNS-01 challenge
certimate_server | 2024/09/23 06:21:24 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/407266369896
certimate_server | 2024/09/23 06:21:25 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/407266369906

**Comment by FunnyFly-ZW** [comment]
+1

**Comment by hqzh** [comment]
腾讯云申请的域名，cf托管和申请的https怎么破呢

**Comment by LancerComet** [comment]
我看了一下 certimate 使用的 lego 库，以 namesilo 为例，里面可以通过读取环境变量来设置超时时间：

https://github.com/go-acme/lego/blob/master/providers/dns/namesilo/namesilo.go#L26

文档也建议给 namesilo 设置超过 15 分钟的时间：https://go-acme.github.io/lego/dns/namesilo/

我随便设置了一个 60000，然后超时时间便被设定在了 16 小时 40 分，即 60000 秒

供参考

**Comment by usual2970** [comment]
感谢反馈～ 可使用 v0.2.0

注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改
