### ISSUE TITLE
[Bug] 腾讯云cdn部署过程日志记录错误

### ISSUE THREAD

**Issue by LeoChen98** [usual2970/certimate#83]
**描述问题**
腾讯云cdn部署过程中，例如`img.example.com`的域名部署成功（确认过确实成功了），但是日志里记录的是`example-部署成功`。

**复现步骤**
复现该问题的步骤：
正常部署即可

**期望的结果**
记录应为`img.example.com-部署成功`

**截图**
如有可能，请添加截图以帮助解释问题。
![image](https://github.com/user-attachments/assets/f4ea4b2b-633f-4d9b-84cd-c3f8875eae0c)

**环境**
- 操作系统: Windows Server 2012 r2
- 浏览器: Chrome @ 109
- 仓库版本: v0.1.10

**其他信息**
在此处添加关于该问题的任何其他信息。

**Comment by usual2970** [comment]
哦，这里指的是部署名称，不是域名
