### ISSUE TITLE
[Feature] 增加本地部署类型

### ISSUE THREAD

**Issue by imaxwen** [usual2970/certimate#84]
**功能描述**
希望可以增加一个本地部署类型，可以将申请的ssl证书部署到本地某个目录。

**动机**
1、certimate和nginx都是通过docker部署在本机中，本地部署类型可以将certimate中生成的证书部署在certimate容器任意目录，再通过docker volumes挂载至本机任意目录。
2、在本机的再ssh到本机进行部署，必要性不大。
3、如果可能的话，可以在certimate容器中安装docker-cli，这样我们甚至可以在容器中操作宿主机的docker用于reload nginx容器中的nginx进程。

**替代方案**
目前使用ssh部署连接本机的方案替代

**其他信息**
--

**Comment by sgpublic** [comment]
感觉有点过度设计了，ssh 登陆之后 `docker exec nginx nginx reload` 是一样的，acme.sh 都不支持这么搞，而且如果这样的话 docker 所有容器都暴露给 certimate，如果是 ssh 登陆还能限定权限。

**Comment by coderZoe** [comment]
同希望增加这个功能

**Comment by xjpz** [comment]
+1

**Comment by LeoChen98** [comment]
+1

**Comment by usual2970** [comment]
已支持 v0.1.12
