### ISSUE TITLE
[Feature] 提供一些可以相互引用的配置

### ISSUE THREAD

**Issue by asd1161575755** [usual2970/certimate#85]
**功能描述**
创建证书时，可以引用一个`部署服务商授权配置`可以只修改覆盖证书和私钥的文件名即可。

**动机**
主要是一个服务上有十几个域名，只是文件名不同而已，但需要重复的配置

**替代方案**
一个一个录累死

**其他信息**

**Comment by usual2970** [comment]
感谢反馈～ 可使用 v0.2.0

注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改
