### ISSUE TITLE
[Feature] 希望DNS服务商和部署服务商授权管理分开

### ISSUE THREAD

**Issue by fcwys** [usual2970/certimate#87]
**功能描述**
希望DNS服务商和部署服务商授权管理分开

**动机**
考虑到DNS解析服务商和部署服务商不一致的情况，此外为了权限安全会针对DNS解析和部署分布使用不同密钥，分开管理会更为灵活

**替代方案**
无

**其他信息**
无

**Comment by FunnyFly-ZW** [comment]
+1，例如cf的DNS解析+SSH部署证书

**Comment by usual2970** [comment]
感谢反馈～ 可使用 v0.2.0

注意 v0.2.0 对 v0.1.xx 引进了一些不向后兼容的修改
