### ISSUE TITLE
[Feature] 希望添加aws 厂商 以及 cert 托管的证书

### ISSUE THREAD

**Issue by qiuyuetao** [usual2970/certimate#89]
**功能描述**
简要描述你希望添加的功能和相关问题。

**动机**
为什么这个功能对项目有帮助？

**替代方案**
描述你已经考虑过的替代方案。

**其他信息**
在这里添加任何相关的附加信息或截图。

**Comment by allegrox** [comment]
非常需要这个功能

**Comment by qiuyuetao** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by usual2970** [comment]
已支持 v0.2.3 感谢 @fudiwei

**Comment by qiuyuetao** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
