### ISSUE TITLE
[Feature] English version

### ISSUE THREAD

**Issue by usual2970** [usual2970/certimate#96]
**Feature Description**

Provide an English version of Certimate, with the ability to switch between Chinese and English in the future.

**Motivation**

There is a growing number of non-Chinese users who, after installing Certimate, don’t know how to proceed.

#67 

**Alternative Solutions**

null

**Additional Information**

Certimate frontend is implemented using React, and you can use react-i18next to achieve multilingual support for Certimate.

**Comment by Masoud5680949** [comment]
Thanks

**Comment by l123wx** [comment]
这个改造开始了吗，我可以帮忙处理

**Comment by l123wx** [comment]
我提交了一个pr，可以在这里#107 看到当前的进度

**Comment by Masoud5680949** [comment]
Ok that's right 👍
