### ISSUE TITLE
[Bug] ssh key 登录失败?

### ISSUE THREAD

**Issue by you-hengh** [usual2970/certimate#99]
**描述问题**
为了服务器安全, 配置了服务器只允许ssh密钥登录(此服务正常使用), 在Certimate 中 通过ssh部署,把证书上传至服务器, 但是最终部署日志显示
```log
[2024-09-26 09:24:16]
开始检查
[2024-09-26 09:24:16]
获取记录成功
[2024-09-26 09:24:16]
获取授权信息成功
[2024-09-26 09:24:16]
检查通过
[2024-09-26 09:24:16]
开始申请
[2024-09-26 09:24:32]
申请证书成功
证书地址: https://acme-v02.api.letsencrypt.org/acme/cert/xxxxxxxx
[2024-09-26 09:24:32]
保存证书成功
[2024-09-26 09:24:32]
开始部署
[2024-09-26 09:24:32]
部署失败
ssh: no key found
```

**复现步骤**
而且发现一个问题, 在完成ssh部署配置后(每一项都添加了ssh key), 在`授权管理`中, 点击编辑任意`ssh部署`类型的项目, 打开的界面都没有显示key文件, 初步怀疑项目在添加ssh部署的时候 **并没有成功保存上传的ssh key**

**期望的结果**
希望能正常通过ssh key 的方式 上传证书

**截图**
![2024-09-26_09-36-36](https://github.com/user-attachments/assets/5526c70c-c26b-4091-a3d6-007f6ac0ef73)

**环境**
- 操作系统: Ubuntu 20.0.4 服务器版本
- 浏览器: 通过vsocde的端口转发 本地edge(129.0.2792.52)浏览器实现访问 
- 仓库版本: 0.1.11

**其他信息**
我的证书格式是pem 请求上传证书的时候 支持pem格式的证书
![2024-09-26_09-51-57](https://github.com/user-attachments/assets/aff2cb65-b101-492e-a62d-6cca81b457a6)

**Comment by Chuyio** [comment]
是的，通过docker部署也是这样ssh: no key found，系统centos7.9

**Comment by usual2970** [comment]
@Chuyio @you-hengh 这里要选私钥，不是公钥
